In [2]:
import pandas as pd

In [3]:
cuestionario_1 = pd.read_excel("CUESTIONARIOS_AFRO.xlsx",sheet_name=0)
cuestionario_2 = pd.read_excel("CUESTIONARIOS_AFRO.xlsx",sheet_name=1)
cuestionario_3 = pd.read_excel("CUESTIONARIOS_AFRO.xlsx",sheet_name=2)

In [4]:
cuestionario_1["base_de_datos"] = "1"
cuestionario_2["base_de_datos"] = "2"
cuestionario_3["base_de_datos"] = "3"

In [5]:
df_afro_clean = pd.read_excel("df_afro_clean_11Marzo2026.xlsx")

In [6]:
df_afro_clean["base_de_datos"] = "0"

In [7]:
cuestionario_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1590 entries, 0 to 1589
Data columns (total 54 columns):
 #   Column                                                                                                                                         Non-Null Count  Dtype
---  ------                                                                                                                                         --------------  -----
 0   Tipo Identificación                                                                                                                            1590 non-null   object
 1   Lugar de nacimiento                                                                                                                            1590 non-null   object
 2   Edad                                                                                                                                           1590 non-null   int64
 3   Genero                                                                                                                                         1590 non-null   object
 4   Nivel de escolaridad                                                                                                                           1590 non-null   object
 5   ¿A que regimen pertenece?                                                                                                                      1589 non-null   object
 6   Ocupación y/o actividad económica                                                                                                              1590 non-null   object
 7   ¿Usted continuamente toma medicinas para  la diabetes?                                                                                         1590 non-null   object
 8   ¿Ha tenido diabetes solo durante el embarazo?                                                                                                  1590 non-null   object
 9   ¿Algún médico le ha diagnosticado tensión arterial alta?                                                                                       1590 non-null   object
 10   ¿Usted continuamente toma medicinas para la presión arterial alta?                                                                            1590 non-null   object
 11  ¿Algún médico le ha diagnosticado colesterol alto?                                                                                             1590 non-null   object
 12  ¿Usted continuamente toma medicinas para el colesterol alto?                                                                                   1590 non-null   object
 13  ¿Algún médico le ha diagnosticado insuficiencia renal crónica? (No incluye piedras en el riñón, infecciones urinarias incontinencia urinaria)  1590 non-null   object
 14  ¿Usted alguna vez ha estado en tratamiento en diálisis?                                                                                        1590 non-null   object
 15  ¿Algún médico le ha diagnosticado proteína o sangre en la orina?                                                                               1590 non-null   object
 16  ¿Eres alérgico algún tipo de medicamento, alimento o producto?                                                                                 1590 non-null   object
 17  En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.                                                                1590 non-null   object
 18  ¿Consume tabaco o cigarrillo?                                                                                                                  1590 non-null   object
 19  ¿Ha fumado al menos 100 cigarrillos durante su vida?                                                                                           1590 non-null   object
 20  ¿Por cuántos años ha sido o fue fumador? días Años                                                                                             1590 non-null   object
 21  ¿Consume alcohol?                                                                                                                              1590 non-null   object
 22  ¿Con que frecuencia usted toma algún tipo debida alcohólica?                                                                                   1590 non-null   object
 23  ¿Toma hasta embriagarse?                                                                                                                       1590 non-null   object
 24  ¿Consume drogas?                                                                                                                               1590 non-null   object
 25  ¿Alguna vez ha laborado en campos de cultivo?                                                                                                  1590 non-null   object
 26  ¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?                                                    1590 non-null   object
 27  ¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?                                                    1590 non-null   object
 28  ¿Usted utiliza o ha utilizado abonos y/o fertilizantes?                                                                                        1590 non-null   object
 29  ¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?                                                                        1590 non-null   object
 30  ¿Qué método utilizó para aplicar estos pesticidas?                                                                                             1590 non-null   object
 31  Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?                                                       1590 non-null   object
 32  Durante su trabajo ¿Qué cantidad de líquido consume?                                                                                           1590 non-null   object
 33  ¿Cuándo fue la última vez que visitó a un doctor?                                                                                              1590 non-null   object
 34  ¿Qué tan difícil es para usted tener atención médica?                                                                                          1590 non-null   object
 35  ¿Qué tipo de profesional de salud ha visitado últimamente?                                                                                     1590 non-null   object
 36  ¿Usted cuenta con un médico de cabecera?                                                                                                       1590 non-null   object
 37  ¿A qué grupo sanguíneo pertenece?                                                                                                              1590 non-null   object
 38  ¿Ha hecho transfusiones previas?                                                                                                               1590 non-null   object
 39  ¿Algún miembro de su familia sufre alguna enfermedad?                                                                                          1590 non-null   object
 40  ¿Algún miembro de su familia tiene insuficiencia renal?                                                                                        1590 non-null   object
 41  Algún miembro de su familia esta en diálisis?                                                                                                  1590 non-null   object
 42  ¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?             1590 non-null   object
 43  ¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?                                                                    1590 non-null   object
 44  ¿Usó medicamentos naturales de forma cotidiana durante el último año?                                                                          1590 non-null   object
 45  ¿Cuál es tu fuente de agua en el hogar?                                                                                                        1590 non-null   object
 46  Presion Arterial                                                                                                                               1542 non-null   object
 47  Peso                                                                                                                                           1590 non-null   int64
 48  Talla                                                                                                                                          1590 non-null   float64
 49  Indice de masa corporal                                                                                                                        1589 non-null   object
 50  Tirilla reactiva                                                                                                                               1590 non-null   object
 51  Creatinina (mg/dL)                                                                                                                             1590 non-null   object
 52  Tasa de filtración glomerular (CDK-EPI)                                                                                                        470 non-null    float64
 53  base_de_datos                                                                                                                                  1590 non-null   object
dtypes: float64(2), int64(2), object(50)
memory usage: 670.9+ KB

In [8]:
cuestionario_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 55 columns):
 #   Column                                                                                                                                         Non-Null Count  Dtype
---  ------                                                                                                                                         --------------  -----
 0   Tipo Identificación                                                                                                                            318 non-null    object
 1   Lugar de nacimiento                                                                                                                            318 non-null    object
 2   Fecha de nacimiento                                                                                                                            318 non-null    object
 3   Edad                                                                                                                                           318 non-null    int64
 4   Genero                                                                                                                                         318 non-null    object
 5   Nivel de escolaridad                                                                                                                           318 non-null    object
 6   ¿A que regimen pertenece?                                                                                                                      318 non-null    object
 7   Ocupación y/o actividad económica                                                                                                              318 non-null    object
 8   ¿Usted continuamente toma medicinas para  la diabetes?                                                                                         318 non-null    object
 9   ¿Ha tenido diabetes solo durante el embarazo?                                                                                                  318 non-null    object
 10  ¿Algún médico le ha diagnosticado tensión arterial alta?                                                                                       318 non-null    object
 11   ¿Usted continuamente toma medicinas para la presión arterial alta?                                                                            318 non-null    object
 12  ¿Algún médico le ha diagnosticado colesterol alto?                                                                                             318 non-null    object
 13  ¿Usted continuamente toma medicinas para el colesterol alto?                                                                                   318 non-null    object
 14  ¿Algún médico le ha diagnosticado insuficiencia renal crónica? (No incluye piedras en el riñón, infecciones urinarias incontinencia urinaria)  318 non-null    object
 15  ¿Usted alguna vez ha estado en tratamiento en diálisis?                                                                                        318 non-null    object
 16  ¿Algún médico le ha diagnosticado proteína o sangre en la orina?                                                                               318 non-null    object
 17  ¿Eres alérgico algún tipo de medicamento, alimento o producto?                                                                                 318 non-null    object
 18  En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.                                                                318 non-null    object
 19  ¿Consume tabaco o cigarrillo?                                                                                                                  318 non-null    object
 20  ¿Ha fumado al menos 100 cigarrillos durante su vida?                                                                                           318 non-null    object
 21  ¿Por cuántos años ha sido o fue fumador? días Años                                                                                             318 non-null    object
 22  ¿Consume alcohol?                                                                                                                              318 non-null    object
 23  ¿Con que frecuencia usted toma algún tipo debida alcohólica?                                                                                   318 non-null    object
 24  ¿Toma hasta embriagarse?                                                                                                                       318 non-null    object
 25  ¿Consume drogas?                                                                                                                               318 non-null    object
 26  ¿Alguna vez ha laborado en campos de cultivo?                                                                                                  318 non-null    object
 27  ¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?                                                    318 non-null    object
 28  ¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?                                                    318 non-null    object
 29  ¿Usted utiliza o ha utilizado abonos y/o fertilizantes?                                                                                        318 non-null    object
 30  ¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?                                                                        318 non-null    object
 31  ¿Qué método utilizó para aplicar estos pesticidas?                                                                                             318 non-null    object
 32  Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?                                                       318 non-null    object
 33  Durante su trabajo ¿Qué cantidad de líquido consume?                                                                                           318 non-null    object
 34  ¿Cuándo fue la última vez que visitó a un doctor?                                                                                              318 non-null    object
 35  ¿Qué tan difícil es para usted tener atención médica?                                                                                          318 non-null    object
 36  ¿Qué tipo de profesional de salud ha visitado últimamente?                                                                                     318 non-null    object
 37  ¿Usted cuenta con un médico de cabecera?                                                                                                       318 non-null    object
 38  ¿A qué grupo sanguíneo pertenece?                                                                                                              318 non-null    object
 39  ¿Ha hecho transfusiones previas?                                                                                                               318 non-null    object
 40  ¿Algún miembro de su familia sufre alguna enfermedad?                                                                                          318 non-null    object
 41  ¿Algún miembro de su familia tiene insuficiencia renal?                                                                                        318 non-null    object
 42  Algún miembro de su familia esta en diálisis?                                                                                                  318 non-null    object
 43  ¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?             318 non-null    object
 44  ¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?                                                                    318 non-null    object
 45  ¿Usó medicamentos naturales de forma cotidiana durante el último año?                                                                          318 non-null    object
 46  ¿Cuál es tu fuente de agua en el hogar?                                                                                                        318 non-null    object
 47  Presion Arterial                                                                                                                               316 non-null    object
 48  Peso                                                                                                                                           318 non-null    int64
 49  Talla                                                                                                                                          318 non-null    float64
 50  Indice de masa corporal                                                                                                                        318 non-null    float64
 51  Tirilla reactiva                                                                                                                               318 non-null    object
 52  Creatinina (mg/dL)                                                                                                                             318 non-null    float64
 53  APOL-1                                                                                                                                         318 non-null    object
 54  base_de_datos                                                                                                                                  318 non-null    object
dtypes: float64(3), int64(2), object(50)
memory usage: 136.8+ KB

In [9]:
cuestionario_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 55 columns):
 #   Column                                                                                                                                         Non-Null Count  Dtype
---  ------                                                                                                                                         --------------  -----
 0   Tipo Identificación                                                                                                                            84 non-null     object
 1   Lugar de nacimiento                                                                                                                            84 non-null     object
 2   Fecha de nacimiento                                                                                                                            84 non-null     datetime64[ns]
 3   Edad                                                                                                                                           84 non-null     int64
 4   Genero                                                                                                                                         84 non-null     object
 5   Nivel de escolaridad                                                                                                                           84 non-null     object
 6   ¿A que regimen pertenece?                                                                                                                      84 non-null     object
 7   Ocupación y/o actividad económica                                                                                                              84 non-null     object
 8   ¿Usted continuamente toma medicinas para  la diabetes?                                                                                         84 non-null     object
 9   ¿Ha tenido diabetes solo durante el embarazo?                                                                                                  84 non-null     object
 10  ¿Algún médico le ha diagnosticado tensión arterial alta?                                                                                       84 non-null     object
 11   ¿Usted continuamente toma medicinas para la presión arterial alta?                                                                            84 non-null     object
 12  ¿Algún médico le ha diagnosticado colesterol alto?                                                                                             84 non-null     object
 13  ¿Usted continuamente toma medicinas para el colesterol alto?                                                                                   84 non-null     object
 14  ¿Algún médico le ha diagnosticado insuficiencia renal crónica? (No incluye piedras en el riñón, infecciones urinarias incontinencia urinaria)  84 non-null     object
 15  ¿Usted alguna vez ha estado en tratamiento en diálisis?                                                                                        84 non-null     object
 16  ¿Algún médico le ha diagnosticado proteína o sangre en la orina?                                                                               84 non-null     object
 17  ¿Eres alérgico algún tipo de medicamento, alimento o producto?                                                                                 84 non-null     object
 18  En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.                                                                84 non-null     object
 19  ¿Consume tabaco o cigarrillo?                                                                                                                  84 non-null     object
 20  ¿Ha fumado al menos 100 cigarrillos durante su vida?                                                                                           84 non-null     object
 21  ¿Por cuántos años ha sido o fue fumador? días Años                                                                                             84 non-null     object
 22  ¿Consume alcohol?                                                                                                                              84 non-null     object
 23  ¿Con que frecuencia usted toma algún tipo debida alcohólica?                                                                                   84 non-null     object
 24  ¿Toma hasta embriagarse?                                                                                                                       84 non-null     object
 25  ¿Consume drogas?                                                                                                                               84 non-null     object
 26  ¿Alguna vez ha laborado en campos de cultivo?                                                                                                  84 non-null     object
 27  ¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?                                                    84 non-null     object
 28  ¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?                                                    84 non-null     object
 29  ¿Usted utiliza o ha utilizado abonos y/o fertilizantes?                                                                                        84 non-null     object
 30  ¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?                                                                        84 non-null     object
 31  ¿Qué método utilizó para aplicar estos pesticidas?                                                                                             84 non-null     object
 32  Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?                                                       84 non-null     object
 33  Durante su trabajo ¿Qué cantidad de líquido consume?                                                                                           84 non-null     object
 34  ¿Cuándo fue la última vez que visitó a un doctor?                                                                                              84 non-null     object
 35  ¿Qué tan difícil es para usted tener atención médica?                                                                                          84 non-null     object
 36  ¿Qué tipo de profesional de salud ha visitado últimamente?                                                                                     84 non-null     object
 37  ¿Usted cuenta con un médico de cabecera?                                                                                                       84 non-null     object
 38  ¿A qué grupo sanguíneo pertenece?                                                                                                              84 non-null     object
 39  ¿Ha hecho transfusiones previas?                                                                                                               84 non-null     object
 40  ¿Algún miembro de su familia sufre alguna enfermedad?                                                                                          84 non-null     object
 41  ¿Algún miembro de su familia tiene insuficiencia renal?                                                                                        84 non-null     object
 42  Algún miembro de su familia esta en diálisis?                                                                                                  84 non-null     object
 43  ¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?             84 non-null     object
 44  ¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?                                                                    84 non-null     object
 45  ¿Usó medicamentos naturales de forma cotidiana durante el último año?                                                                          84 non-null     object
 46  ¿Cuál es tu fuente de agua en el hogar?                                                                                                        84 non-null     object
 47  Presion Arterial                                                                                                                               83 non-null     object
 48  Peso                                                                                                                                           84 non-null     int64
 49  Talla                                                                                                                                          84 non-null     float64
 50  Indice de masa corporal                                                                                                                        84 non-null     float64
 51  Tirilla reactiva                                                                                                                               84 non-null     object
 52  Creatinina (mg/dL)                                                                                                                             84 non-null     float64
 53  APOL-1                                                                                                                                         84 non-null     object
 54  base_de_datos                                                                                                                                  84 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(2), object(49)
memory usage: 36.2+ KB

In [10]:
df_afro_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2397 entries, 0 to 2396
Data columns (total 32 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   edad                                      2397 non-null   int64
 1   genero                                    2397 non-null   object
 2   nivel_escolaridad                         2397 non-null   object
 3   regimen_salud                             2397 non-null   object
 4   ocupacion                                 2397 non-null   object
 5   medicinas_para_diabetes                   2397 non-null   object
 6   diabetes_durante_embarazo                 2397 non-null   object
 7   antecedentes_presion_alta                 2397 non-null   object
 8   medicinas_presion_arterial                2397 non-null   object
 9   medicinas_colesterol_alto                 2397 non-null   object
 10  transfusiones_previas                     2397 non-null   object
 11  diagnostico_insuficiencia_renal_cronica   2397 non-null   object
 12  diagnostico_proteina_sangre_orina         2397 non-null   object
 13  antecedentes_familia_insuficiencia_renal  2397 non-null   object
 14  antecedentes_familia_dialisis             2397 non-null   object
 15  consume_tabaco                            2397 non-null   object
 16  años_fumador                              850 non-null    object
 17  consume_alcohol                           2397 non-null   object
 18  frecuencia_consumo_alcohol                2397 non-null   object
 19  toma_hasta_embriagarse                    2397 non-null   object
 20  consumo_liquidos_durante_trabajo          2397 non-null   object
 21  peso                                      2397 non-null   float64
 22  talla                                     2397 non-null   float64
 23  imc                                       2397 non-null   float64
 24  presion_arterial_sistolica                2345 non-null   float64
 25  presion_arterial_diastolica               2345 non-null   float64
 26  creatinina                                1302 non-null   float64
 27  tirilla_reactiva                          2397 non-null   object
 28  tasa_filtracion_glomerular                1302 non-null   float64
 29  departamento_georeferenciacion            2346 non-null   object
 30  municipio_georeferenciacion               2346 non-null   object
 31  base_de_datos                             2397 non-null   object
dtypes: float64(7), int64(1), object(24)
memory usage: 599.4+ KB

In [11]:
print("En c1 y no en c2:", set(cuestionario_1.columns) - set(cuestionario_2.columns))
print("En c2 y no en c1:", set(cuestionario_2.columns) - set(cuestionario_1.columns))

print("En c1 y no en c3:", set(cuestionario_1.columns) - set(cuestionario_3.columns))
print("En c3 y no en c1:", set(cuestionario_3.columns) - set(cuestionario_1.columns))

En c1 y no en c2: {'Tasa de filtración glomerular (CDK-EPI)'}
En c2 y no en c1: {'Fecha de nacimiento', 'APOL-1'}
En c1 y no en c3: {'Tasa de filtración glomerular (CDK-EPI)'}
En c3 y no en c1: {'Fecha de nacimiento', 'APOL-1'}

In [12]:
todas_columnas = set(cuestionario_1.columns) | set(cuestionario_2.columns) | set(cuestionario_3.columns)

In [13]:
for col in todas_columnas:
    if col not in cuestionario_1.columns:
        cuestionario_1[col] = "Desconocido"
        
    if col not in cuestionario_2.columns:
        cuestionario_2[col] = "Desconocido"
        
    if col not in cuestionario_3.columns:
        cuestionario_3[col] = "Desconocido"

In [14]:
df_total = pd.concat([cuestionario_1, cuestionario_2, cuestionario_3], ignore_index=True)

In [15]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1992 entries, 0 to 1991
Data columns (total 56 columns):
 #   Column                                                                                                                                         Non-Null Count  Dtype
---  ------                                                                                                                                         --------------  -----
 0   Tipo Identificación                                                                                                                            1992 non-null   object
 1   Lugar de nacimiento                                                                                                                            1992 non-null   object
 2   Edad                                                                                                                                           1992 non-null   int64
 3   Genero                                                                                                                                         1992 non-null   object
 4   Nivel de escolaridad                                                                                                                           1992 non-null   object
 5   ¿A que regimen pertenece?                                                                                                                      1991 non-null   object
 6   Ocupación y/o actividad económica                                                                                                              1992 non-null   object
 7   ¿Usted continuamente toma medicinas para  la diabetes?                                                                                         1992 non-null   object
 8   ¿Ha tenido diabetes solo durante el embarazo?                                                                                                  1992 non-null   object
 9   ¿Algún médico le ha diagnosticado tensión arterial alta?                                                                                       1992 non-null   object
 10   ¿Usted continuamente toma medicinas para la presión arterial alta?                                                                            1992 non-null   object
 11  ¿Algún médico le ha diagnosticado colesterol alto?                                                                                             1992 non-null   object
 12  ¿Usted continuamente toma medicinas para el colesterol alto?                                                                                   1992 non-null   object
 13  ¿Algún médico le ha diagnosticado insuficiencia renal crónica? (No incluye piedras en el riñón, infecciones urinarias incontinencia urinaria)  1992 non-null   object
 14  ¿Usted alguna vez ha estado en tratamiento en diálisis?                                                                                        1992 non-null   object
 15  ¿Algún médico le ha diagnosticado proteína o sangre en la orina?                                                                               1992 non-null   object
 16  ¿Eres alérgico algún tipo de medicamento, alimento o producto?                                                                                 1992 non-null   object
 17  En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.                                                                1992 non-null   object
 18  ¿Consume tabaco o cigarrillo?                                                                                                                  1992 non-null   object
 19  ¿Ha fumado al menos 100 cigarrillos durante su vida?                                                                                           1992 non-null   object
 20  ¿Por cuántos años ha sido o fue fumador? días Años                                                                                             1992 non-null   object
 21  ¿Consume alcohol?                                                                                                                              1992 non-null   object
 22  ¿Con que frecuencia usted toma algún tipo debida alcohólica?                                                                                   1992 non-null   object
 23  ¿Toma hasta embriagarse?                                                                                                                       1992 non-null   object
 24  ¿Consume drogas?                                                                                                                               1992 non-null   object
 25  ¿Alguna vez ha laborado en campos de cultivo?                                                                                                  1992 non-null   object
 26  ¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?                                                    1992 non-null   object
 27  ¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?                                                    1992 non-null   object
 28  ¿Usted utiliza o ha utilizado abonos y/o fertilizantes?                                                                                        1992 non-null   object
 29  ¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?                                                                        1992 non-null   object
 30  ¿Qué método utilizó para aplicar estos pesticidas?                                                                                             1992 non-null   object
 31  Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?                                                       1992 non-null   object
 32  Durante su trabajo ¿Qué cantidad de líquido consume?                                                                                           1992 non-null   object
 33  ¿Cuándo fue la última vez que visitó a un doctor?                                                                                              1992 non-null   object
 34  ¿Qué tan difícil es para usted tener atención médica?                                                                                          1992 non-null   object
 35  ¿Qué tipo de profesional de salud ha visitado últimamente?                                                                                     1992 non-null   object
 36  ¿Usted cuenta con un médico de cabecera?                                                                                                       1992 non-null   object
 37  ¿A qué grupo sanguíneo pertenece?                                                                                                              1992 non-null   object
 38  ¿Ha hecho transfusiones previas?                                                                                                               1992 non-null   object
 39  ¿Algún miembro de su familia sufre alguna enfermedad?                                                                                          1992 non-null   object
 40  ¿Algún miembro de su familia tiene insuficiencia renal?                                                                                        1992 non-null   object
 41  Algún miembro de su familia esta en diálisis?                                                                                                  1992 non-null   object
 42  ¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?             1992 non-null   object
 43  ¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?                                                                    1992 non-null   object
 44  ¿Usó medicamentos naturales de forma cotidiana durante el último año?                                                                          1992 non-null   object
 45  ¿Cuál es tu fuente de agua en el hogar?                                                                                                        1992 non-null   object
 46  Presion Arterial                                                                                                                               1941 non-null   object
 47  Peso                                                                                                                                           1992 non-null   int64
 48  Talla                                                                                                                                          1992 non-null   float64
 49  Indice de masa corporal                                                                                                                        1991 non-null   object
 50  Tirilla reactiva                                                                                                                               1992 non-null   object
 51  Creatinina (mg/dL)                                                                                                                             1992 non-null   object
 52  Tasa de filtración glomerular (CDK-EPI)                                                                                                        872 non-null    object
 53  base_de_datos                                                                                                                                  1992 non-null   object
 54  Fecha de nacimiento                                                                                                                            1992 non-null   object
 55  APOL-1                                                                                                                                         1992 non-null   object
dtypes: float64(1), int64(2), object(53)
memory usage: 871.6+ KB

In [16]:
df_total.columns

Index(['Tipo Identificación', 'Lugar de nacimiento ', 'Edad', 'Genero ',
       'Nivel de escolaridad', '¿A que regimen pertenece?',
       'Ocupación y/o actividad económica',
       '¿Usted continuamente toma medicinas para  la diabetes?',
       '¿Ha tenido diabetes solo durante el embarazo?',
       '¿Algún médico le ha diagnosticado tensión arterial alta?',
       ' ¿Usted continuamente toma medicinas para la presión arterial alta?',
       '¿Algún médico le ha diagnosticado colesterol alto?',
       '¿Usted continuamente toma medicinas para el colesterol alto?',
       '¿Algún médico le ha diagnosticado insuficiencia renal crónica? (No incluye piedras en el riñón, infecciones urinarias incontinencia urinaria)',
       '¿Usted alguna vez ha estado en tratamiento en diálisis?',
       '¿Algún médico le ha diagnosticado proteína o sangre en la orina?',
       '¿Eres alérgico algún tipo de medicamento, alimento o producto?',
       'En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.',
       '¿Consume tabaco o cigarrillo?',
       '¿Ha fumado al menos 100 cigarrillos durante su vida?',
       '¿Por cuántos años ha sido o fue fumador? días Años',
       '¿Consume alcohol?',
       '¿Con que frecuencia usted toma algún tipo debida alcohólica? ',
       '¿Toma hasta embriagarse?', '¿Consume drogas?',
       '¿Alguna vez ha laborado en campos de cultivo?',
       '¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?',
       '¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?',
       '¿Usted utiliza o ha utilizado abonos y/o fertilizantes?',
       '¿Al usar estos pesticidas, usó alguna vestimenta o protección especial? ',
       '¿Qué método utilizó para aplicar estos pesticidas? ',
       'Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?',
       'Durante su trabajo ¿Qué cantidad de líquido consume?',
       '¿Cuándo fue la última vez que visitó a un doctor?',
       '¿Qué tan difícil es para usted tener atención médica?',
       '¿Qué tipo de profesional de salud ha visitado últimamente?',
       '¿Usted cuenta con un médico de cabecera?',
       '¿A qué grupo sanguíneo pertenece?', '¿Ha hecho transfusiones previas?',
       '¿Algún miembro de su familia sufre alguna enfermedad?',
       '¿Algún miembro de su familia tiene insuficiencia renal?',
       'Algún miembro de su familia esta en diálisis?',
       '¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda? ',
       '¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?',
       '¿Usó medicamentos naturales de forma cotidiana durante el último año? ',
       '¿Cuál es tu fuente de agua en el hogar?', 'Presion Arterial', 'Peso',
       'Talla', 'Indice de masa corporal', 'Tirilla reactiva ',
       'Creatinina (mg/dL)', 'Tasa de filtración glomerular (CDK-EPI)',
       'base_de_datos', 'Fecha de nacimiento', 'APOL-1'],
      dtype='object')

In [17]:
pd.set_option('display.max_columns', None)
df_total.head()

,Tipo Identificación,Lugar de nacimiento,Edad,Genero,Nivel de escolaridad,¿A que regimen pertenece?,Ocupación y/o actividad económica,¿Usted continuamente toma medicinas para la diabetes?,¿Ha tenido diabetes solo durante el embarazo?,¿Algún médico le ha diagnosticado tensión arterial alta?,¿Usted continuamente toma medicinas para la presión arterial alta?,¿Algún médico le ha diagnosticado colesterol alto?,¿Usted continuamente toma medicinas para el colesterol alto?,"¿Algún médico le ha diagnosticado insuficiencia renal crónica? (No incluye piedras en el riñón, infecciones urinarias incontinencia urinaria)",¿Usted alguna vez ha estado en tratamiento en diálisis?,¿Algún médico le ha diagnosticado proteína o sangre en la orina?,"¿Eres alérgico algún tipo de medicamento, alimento o producto?","En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.",¿Consume tabaco o cigarrillo?,¿Ha fumado al menos 100 cigarrillos durante su vida?,¿Por cuántos años ha sido o fue fumador? días Años,¿Consume alcohol?,¿Con que frecuencia usted toma algún tipo debida alcohólica?,¿Toma hasta embriagarse?,¿Consume drogas?,¿Alguna vez ha laborado en campos de cultivo?,¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?,¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?,¿Usted utiliza o ha utilizado abonos y/o fertilizantes?,"¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?",¿Qué método utilizó para aplicar estos pesticidas?,Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?,Durante su trabajo ¿Qué cantidad de líquido consume?,¿Cuándo fue la última vez que visitó a un doctor?,¿Qué tan difícil es para usted tener atención médica?,¿Qué tipo de profesional de salud ha visitado últimamente?,¿Usted cuenta con un médico de cabecera?,¿A qué grupo sanguíneo pertenece?,¿Ha hecho transfusiones previas?,¿Algún miembro de su familia sufre alguna enfermedad?,¿Algún miembro de su familia tiene insuficiencia renal?,Algún miembro de su familia esta en diálisis?,"¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?",¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?,¿Usó medicamentos naturales de forma cotidiana durante el último año?,¿Cuál es tu fuente de agua en el hogar?,Presion Arterial,Peso,Talla,Indice de masa corporal,Tirilla reactiva,Creatinina (mg/dL),Tasa de filtración glomerular (CDK-EPI),base_de_datos,Fecha de nacimiento,APOL-1
0,CEDULA,"Bolívar, María La Baja",57,FEMENINO,Primaria,Subsidiado,Desempleado,Si,No,Si,Si,Si,Si,No,No,No,No,No aplica,No,No,No aplica,No,Nunca,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 1 litro,Mayor a 3 meses,Muy Dificil,Internista,Si,B+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,175/89,63,1.66,22.862534,Negativo,0.9,82.26,1,Desconocido,Desconocido
1,CEDULA,"Barranquilla, Atlántico",28,FEMENINO,Secundaria,Subsidiado,Desempleado,No,Sí,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por mes,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 200 cc,Mayor a 3 meses,Difícil,Medico General,No,O+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,97/70,75,1.63,28.228386,Negativo,0.7,116.28,1,Desconocido,Desconocido
2,CEDULA,"Barranquilla, Atlántico",35,FEMENINO,Bachiller,Subsidiado,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por semana,No,No,No,No,No,No,No aplica,No aplica,Dolor de cabeza,Mas de 1 litro,Mayor a dos años,Facil,Medico General,No,O+,No,Hipertensión Arterial,Sí,No,Dolor de cabeza,Si,Si,Suministro municipal,92/68,97,1.68,34.367914,Negativo,No realizado,NaN,1,Desconocido,Desconocido
3,CEDULA,"Ciénaga, Magdalena",19,FEMENINO,Primaria,No tiene,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por mes,No,No,No,No,No,No,No aplica,No aplica,No siente nada,No toma nada,Mayor a dos años,Muy Dificil,Medico General,No,A+,No,Diabetes Mellitus,No,No,Dolor de cabeza,Si,Si,Suministro municipal,105/63,65,1.62,24.767566,Negativo,No realizado,NaN,1,Desconocido,Desconocido
4,CEDULA,"San Jacinto, Bolívar",44,FEMENINO,Bachiller,Subsidiado,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,No,Nunca,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 1 litro,Mayor a dos años,Difícil,Medico General,Si,O+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,126/71,70,1.57,28.398718,Negativo,No realizado,NaN,1,Desconocido,Desconocido

In [18]:
pd.set_option('display.max_columns', None)
df_afro_clean.head()

,edad,genero,nivel_escolaridad,regimen_salud,ocupacion,medicinas_para_diabetes,diabetes_durante_embarazo,antecedentes_presion_alta,medicinas_presion_arterial,medicinas_colesterol_alto,transfusiones_previas,diagnostico_insuficiencia_renal_cronica,diagnostico_proteina_sangre_orina,antecedentes_familia_insuficiencia_renal,antecedentes_familia_dialisis,consume_tabaco,años_fumador,consume_alcohol,frecuencia_consumo_alcohol,toma_hasta_embriagarse,consumo_liquidos_durante_trabajo,peso,talla,imc,presion_arterial_sistolica,presion_arterial_diastolica,creatinina,tirilla_reactiva,tasa_filtracion_glomerular,departamento_georeferenciacion,municipio_georeferenciacion,base_de_datos
0,57,Femenino,Primaria,Asegurador público,Desempleado,SI,NO,SI,SI,SI,NO,NO,NO,NO,NO,NO,NaN,NO,Nunca,Negativa,Mas de 1 litro,63.0,1.66,22.862534,175.0,89.0,0.9,Negativa,82.26,BOLIVAR,MARIA LA BAJA,0
1,28,Femenino,Secundaria,Asegurador público,Desempleado,NO,SI,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,SI,1-2 veces por mes,Negativa,Mas de 200 cc,75.0,1.63,28.228386,97.0,70.0,0.7,Negativa,116.28,ATLANTICO,BARRANQUILLA,0
2,35,Femenino,Bachiller,Asegurador público,Desempleado,NO,NO,NO,NO,NO,NO,NO,NO,SI,NO,NO,NaN,SI,1-2 veces por semana,Negativa,Mas de 1 litro,97.0,1.68,34.367914,92.0,68.0,NaN,Negativa,NaN,ATLANTICO,BARRANQUILLA,0
3,19,Femenino,Primaria,No asegurado,Desempleado,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,SI,1-2 veces por mes,Negativa,No toma nada,65.0,1.62,24.767566,105.0,63.0,NaN,Negativa,NaN,ATLANTICO,BARRANQUILLA,0
4,44,Femenino,Bachiller,Asegurador público,Desempleado,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,NO,Nunca,Negativa,Mas de 1 litro,70.0,1.57,28.398718,126.0,71.0,NaN,Negativa,NaN,ATLANTICO,BARRANQUILLA,0

In [19]:
df_total[["presion_arterial_sistolica","presion_arterial_diastolica"]] = df_total["Presion Arterial"].str.split("/", expand=True)
df_total["presion_arterial_sistolica"] = pd.to_numeric(df_total["presion_arterial_sistolica"], errors="coerce")
df_total["presion_arterial_diastolica"] = pd.to_numeric(df_total["presion_arterial_diastolica"], errors="coerce")
df_total = df_total.drop(columns="Presion Arterial")

In [20]:
col_afro_clean = df_afro_clean.columns

In [21]:
def categorias (df, nombre):
    for i in range(0,len(nombre)):
        if (df[nombre[i]].dtype == "object"):
            print("\n",nombre[i],":")
            print(df[nombre[i]].unique())

In [22]:
df_afro_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2397 entries, 0 to 2396
Data columns (total 32 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   edad                                      2397 non-null   int64
 1   genero                                    2397 non-null   object
 2   nivel_escolaridad                         2397 non-null   object
 3   regimen_salud                             2397 non-null   object
 4   ocupacion                                 2397 non-null   object
 5   medicinas_para_diabetes                   2397 non-null   object
 6   diabetes_durante_embarazo                 2397 non-null   object
 7   antecedentes_presion_alta                 2397 non-null   object
 8   medicinas_presion_arterial                2397 non-null   object
 9   medicinas_colesterol_alto                 2397 non-null   object
 10  transfusiones_previas                     2397 non-null   object
 11  diagnostico_insuficiencia_renal_cronica   2397 non-null   object
 12  diagnostico_proteina_sangre_orina         2397 non-null   object
 13  antecedentes_familia_insuficiencia_renal  2397 non-null   object
 14  antecedentes_familia_dialisis             2397 non-null   object
 15  consume_tabaco                            2397 non-null   object
 16  años_fumador                              850 non-null    object
 17  consume_alcohol                           2397 non-null   object
 18  frecuencia_consumo_alcohol                2397 non-null   object
 19  toma_hasta_embriagarse                    2397 non-null   object
 20  consumo_liquidos_durante_trabajo          2397 non-null   object
 21  peso                                      2397 non-null   float64
 22  talla                                     2397 non-null   float64
 23  imc                                       2397 non-null   float64
 24  presion_arterial_sistolica                2345 non-null   float64
 25  presion_arterial_diastolica               2345 non-null   float64
 26  creatinina                                1302 non-null   float64
 27  tirilla_reactiva                          2397 non-null   object
 28  tasa_filtracion_glomerular                1302 non-null   float64
 29  departamento_georeferenciacion            2346 non-null   object
 30  municipio_georeferenciacion               2346 non-null   object
 31  base_de_datos                             2397 non-null   object
dtypes: float64(7), int64(1), object(24)
memory usage: 599.4+ KB

In [23]:
categorias(df_afro_clean, col_afro_clean)

 genero :
['Femenino' 'Masculino']

 nivel_escolaridad :
['Primaria' 'Secundaria' 'Bachiller' 'No  escolarizado' 'Técnica'
 'Universitaria' 'Posgrado' 'Tecnológa']

 regimen_salud :
['Asegurador público' 'No asegurado' 'Asegurador privado']

 ocupacion :
['Desempleado' 'Otro' 'Agricultor' 'Albañil' 'Comerciante' 'pescador'
 'Ganadero' 'Campesino' 'Albanil' 'Ama de casa ' 'Ama de casa'
 'Servicio generales ' 'Modista ' 'Conductor ' 'Jefe de cartera '
 'Monitora en Deporte ' 'Oficios múltiples' 'AMA DE CASA'
 'AUXILIAR LOGISTICO' 'ESTUDIANTE' 'AMA DE CASA ' 'MANICURISTA'
 'JARDINERO' 'MAESTRO DE ALBAÑILERIA' 'MODISTA' 'ESTILISTA' 'PENSIONADO'
 'ADMINISTRADORA DE EMPRESAS ' 'AUXILIAR DE ENFERMERIA'
 'TECNICO ELECTRONICO' 'COMERCIANTE' 'TRABAJADORA SOCIAL ' 'SECRETARIA'
 'ESTUDIANTE DE ENFERMERIA ' 'TAXISTA' 'ADMINISTRADORA DE EMPRESAS'
 'ADMINISTRADOR DE EMPRESA' 'COCINERO' 'OFICIOS VARIOS '
 'AUXILIAR DE ALMACEN' 'ADMINISTRADOR DE FINCA GANADERA '
 'AUXILIAR DE FARMACIA' 'ADMINISTRADORA DE EMPRESA' 'ASISTENTE DE ARCHIVO'
 'COCINERA' 'MEDICO' 'OFICIOS VARIOS' 'CONTADOR' 'CONDUCTOR'
 'FISIOTERAPEUTA' 'INDEPENDIENTE' 'COORDINADORA DE COMPRAS ' 'COSTURERA'
 'TECNICO EN REFIGERACIÓN' 'PROFESORA ' 'COORDINADOR LOGISTICO '
 'TECNICO ELECTROMECANICO' 'PSICOLOGA' 'COORDINADORA DE GESTIÓN HUMANA '
 'ESTUDIANTE ' 'MERCADERISTA' 'DOCENTE' 'TECNICO DE BANCO DE PROYECTO '
 'PRACTICANTE DE TECNICO' 'ENFERMERA' 'SERVICIOS GENERALES' 'CONDUCTOR '
 'AUXILIAR DE ENFERMERIA ' 'AUDITOR DE PROCESO'
 'TECNOLOGO EN PROCESOS INDUSTRIALES' 'ADMINISTRADOR EN AREA DE SALUD'
 'TECNICO AUXILIAR DE ENFERMERIA ' 'ASESORA COMERCIAL BANCARIA'
 'SUPERVISOR DE VIGILANCIA ' 'TECNOLOGA EN GESTIÓN AMBIENTAL '
 'TECNICO EN ANALISIS Y PROGRAMACIÓN ' 'PSICOLOGA ' 'VENDEDORA AMBULANTE'
 'AUXILIAR PREESCOLAR' 'ABOGADA' 'VENDEDOR AMBULANTE'
 'AGENTE EDUCATIVO DE HOGAR COMUNITARIO' 'ESTUDIANTE DE ENFERMERIA'
 'EMPLEADA' 'CONDUCTOR DE BUS' 'CONTADOR PUBLICO '
 'INGENIERO ELECTROMECANICO' 'GERENTE FINANCIERA' 'ASEADORA' 'PROFESOR'
 'PENSIONADO DE LA ARMADA ' 'CARGAS PESADAS ' 'GUARDA DE SEGURIDAD '
 'CONTRATISTA DE ACABADOS' 'MÚSICO ' 'Pescador' 'ARBITRO' 'POLICIA '
 'ESTUDIANTE UNIVERSITATRIO ' 'CONFECCIONISTA' 'SUPERVISORA DE HOTEL '
 'CONTADORA PUBLICA' 'AUXILIAR DE COCINA' 'SERVICIOS GENERALES '
 'CONSERJE DE IGLESIA' 'ZAPATERO' 'SOLDADOR' 'EMPLEADA DOMESTICA'
 'CONTADOR PUBLICO' 'ASISTENTE ADMINISTRATIVO' 'VIGILANTE'
 'COMUNICADORA SOCIAL' 'CUIDADORA ' 'DESARROLLADOR DE SISTEMAS'
 'ESTUDIANTE ENFERMERIA' 'JUBILADO ' 'HOGAR' 'ZAPATERO '
 'TRABAJADOR EN SUPERMERCADO ' 'JEFE DE COCINA' 'TRABAJADORA SOCIAL'
 'AUXILIAR DE MANTENIMIENTO' 'INDEPENDIENTE ' 'AUXILIAR EN ENFERMERIA'
 'CAJERA' 'ENFERMERIA' 'TRABAJADOR EN DROGUERIA ' 'PENSIONADA'
 'EMPRESARIA ' 'AUXILIAR DE EMPRESAS ' 'CUIDADOR' 'CAMILLERO'
 'SECRETARIA ' 'VENDEDORA' 'EMPLEADA ' 'EMPLEADO' 'CALL CENTER'
 'ADMINISTRATIVA ' 'EMPLEADA DE SERVICIO ' 'Pintor ' 'Independiente '
 'Guarda de seguridad' 'Pensionado' 'Secretaria' 'ama de casa '
 'ARQUITECTO ' 'AMA DE  CASA ' 'CARPINTERO ' 'Conductor' 'ALBAÑIL'
 'MODICTA' 'COCINA' 'AMO DE CASA' 'LATONERO' 'Oficina ' 'ESCOLTA'
 'Operador' 'Ama de Casa ' 'oficios varios' 'electrico' 'conductor'
 'Panadera ' 'VIGILANTE ' 'Mototaxista ' 'DESEMPLEADO' 'Docente '
 'Auxiliar de farmacia ' 'AUXILIAR DE COCINA ' 'MANICURISTA ' 'EMPLEADO '
 'CASA DE FAMILIA ' 'ama de cada' 'ama de casa' 'No trabaja'
 'Manicurista ' 'DOCENTE ' 'electrónico ' 'VENDEDOR DE TINTO' 'MOTOTAXI'
 'Cobrador ' 'Vigilante' 'ELECTRONICA' 'MECANICO' 'Vigilante '
 'Oficios varios ' 'EMPLEADA DOMESTICA ' 'PINTOR']

 medicinas_para_diabetes :
['SI' 'NO']

 diabetes_durante_embarazo :
['NO' 'SI' 'No aplica']

 antecedentes_presion_alta :
['SI' 'NO']

 medicinas_presion_arterial :
['SI' 'NO']

 medicinas_colesterol_alto :
['SI' 'NO']

 transfusiones_previas :
['NO' 'SI']

 diagnostico_insuficiencia_renal_cronica :
['NO' 'SI']

 diagnostico_proteina_sangre_orina :
['NO' 'SI']

 antecedentes_familia_insuficiencia_renal :
['NO' 'SI']

 antecedentes_familia_dialisis :
['NO' 'SI']

 consume_tabaco :
['NO' 'SI']

 años_fumador :
[nan 'No aplica' '5 años o más' '1 - 2 años' '3 - 4 años']

 consume_alcohol :
['NO' 'SI']

 frecuencia_consumo_alcohol :
['Nunca' '1-2 veces por mes' '1-2 veces por semana'
 'Menos de 1 vez por mes' 'Casi diario' '3-4 veces por semana' 'Diario']

 toma_hasta_embriagarse :
['Negativa' 'No aplica' 'Positiva']

 consumo_liquidos_durante_trabajo :
['Mas de 1 litro' 'Mas de 200 cc' 'No toma nada' 'Mas de 5 litros'
 'Menos de 100 cc' 'Más de 200 cc']

 tirilla_reactiva :
['Negativa' 'Positiva']

 departamento_georeferenciacion :
['BOLIVAR' 'ATLANTICO' nan 'LA GUAJIRA' 'MAGDALENA' 'CESAR' 'SUCRE'
 'CORDOBA' 'VALLE DEL CAUCA' 'CAUCA' 'NARIÑO' 'TOLIMA']

 municipio_georeferenciacion :
['MARIA LA BAJA' 'BARRANQUILLA' 'SAN BASILIO DE PALENQUE' 'LOMA DE ARENA'
 'PONTEZUELA' 'SAN JOSE DE SACO' nan 'MAICAO' 'PARAGUACHON' 'PUEBLO VIEJO'
 'EL BANCO' 'SOLEDAD' 'RIOHACHA' 'EL PASO' 'CHIRIGUANA' 'PALMITO'
 'VALLEDUPAR' 'JUAN DE ACOSTA' 'SAHAGUN' 'PUERTO COLOMBIA' 'CALAMAR'
 'CARTAGENA DE INDIAS' 'SUAN' 'LORICA' 'SANTA MARTA' 'SALAMINA' 'BARANOA'
 'SAN JUAN DEL CESAR' 'SABANALARGA' 'GALAPA' 'SABANAGRANDE' 'PUEBLO NUEVO'
 'SAN MARCOS' 'CALI' 'PALMIRA' 'POPAYAN' 'PASTO' 'IBAGUE' 'POLONUEVO'
 'BARRANCA VIEJA' 'EL CARMEN DE BOLIVAR' 'HATO VIEJO' 'BARRANCA NUEVA'
 'ZAMBRANO' 'ASTREA' 'SINCELEJO' 'SANTA LUCIA' 'ALGODONAL' 'CARRETO']

 base_de_datos :
['0']

In [24]:
departamentos= ['BOLIVAR', 'ATLANTICO', 'nan', 'LA GUAJIRA', 'MAGDALENA', 'CESAR', 'SUCRE',
 'CORDOBA', 'VALLE DEL CAUCA', 'CAUCA', 'NARIÑO', 'TOLIMA']

municipios = ['MARIA LA BAJA', 'BARRANQUILLA', 'SAN BASILIO DE PALENQUE', 'LOMA DE ARENA',
 'PONTEZUELA', 'SAN JOSE DE SACO', 'nan', 'MAICAO', 'PARAGUACHON', 'PUEBLO VIEJO',
 'EL BANCO', 'SOLEDAD', 'RIOHACHA', 'EL PASO', 'CHIRIGUANA', 'PALMITO',
 'VALLEDUPAR', 'JUAN DE ACOSTA', 'SAHAGUN', 'PUERTO COLOMBIA', 'CALAMAR',
 'CARTAGENA DE INDIAS', 'SUAN', 'LORICA', 'SANTA MARTA', 'SALAMINA', 'BARANOA',
 'SAN JUAN DEL CESAR', 'SABANALARGA', 'GALAPA', 'SABANAGRANDE', 'PUEBLO NUEVO',
 'SAN MARCOS', 'CALI', 'PALMIRA', 'POPAYAN', 'PASTO', 'IBAGUE', 'POLONUEVO',
 'BARRANCA VIEJA', 'EL CARMEN DE BOLIVAR', 'HATO VIEJO', 'BARRANCA NUEVA',
 'ZAMBRANO', 'ASTREA', 'SINCELEJO', 'SANTA LUCIA', 'ALGODONAL', 'CARRETO']

In [25]:
import re

def encontrar_municipio(texto):

    if pd.isna(texto):
        return None

    texto = str(texto).upper()

    for m in municipios:
        if m in texto:
            return m

    return None


def encontrar_departamento(texto):

    if pd.isna(texto):
        return None

    texto = str(texto).upper()

    for d in departamentos:
        if d in texto:
            return d

    return None

In [26]:
import unicodedata

df_total["Lugar de nacimiento "] = (
    df_total["Lugar de nacimiento "]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
    .encode('ascii', 'ignore')
    .decode('utf-8')
    .upper())
)

In [27]:
df_total["Lugar de nacimiento "].unique()

array(['BOLIVAR, MARIA LA BAJA', 'BARRANQUILLA, ATLANTICO',
       'CIENAGA, MAGDALENA', 'SAN JACINTO, BOLIVAR', 'BARRANQUILLA ',
       'SAN BASILIO DE PALENQUE, BOLIVAR', 'BARRANQUILLA', 'PALENQUE ',
       'SAN ONOFRE SUCRE ', 'BARRANQUILLA ATLANTICO ', 'MONTERIA ',
       'PUERTO COLOMBIA ', 'SAN PABLO (BOLIVAR)', 'ADANZASU, CALDAS',
       'TUBARA, ATLANTICO', 'ZAMBRANO, BOLIVAR  ', 'SAN PABLO BOLIVAR ',
       'TOLU SUCRE', 'VENEZUELA', 'SANTA ANA MAGDALENA ', 'SINCELEJO ',
       'CARTAGENA ', 'SANGUN CORDOBA ', 'TENERIFE MAGDALENA ',
       'SAGAHUN, CORDOBA ', 'ARENAL', 'TRUJILLO VENEZUELA ', 'BARANOA',
       'SUCRE', 'BOLIVAR ', 'MAHATE (BOLIVAR)', 'MARIA LA BAJA BOLIVAR ',
       'BOMBA, MAGDALENA ', 'CARACAS VENEZUELA ', 'VENEZUELA ',
       'GUARANDA ', 'MARIA LA BAJA', 'OVEJAS, SUCRE ', 'CARTAGENA',
       'EL AGARRON, MAGDALENA ', 'SANTA LUCIA ATLANTICO ',
       'EL CARMEN DE BOLIVAR', 'MARIA LA BAJA (BOLIVAR)',
       'TIERRA ALTA CORDOBA ', 'VILLA ROSA REPELON ATLANTICO',
       'PLATO MAGDALENA ', 'IBAGUE TOLIMA', 'SAN ESTANISLAO BOLIVAR ',
       'MARIA LA BAJA BOLIVAR', 'MOMPOX', 'CARACAS, VENEZUELA ',
       'BARRO BLANCO MAGDALENA ', 'MARACAIBO VENEZUELA ', 'SABANA LARGA ',
       'SOLEDAD ATLANTICO ', 'QUIMBAYA QUINDIO ', 'TACAMOCHO BOLIVAR ',
       'PALENQUE', 'BARRANQUUILLA', 'CARTAGENA BOLIVAR', 'VALLEDUPAR',
       'CARTAGENA -BOLIVAR', 'MARIALABAJA / BOLIVAR', 'MAHATES BOLIVAR',
       'CARTAGENA - BOLIVAR', 'MONTERIA', 'GALERAZAMBA', 'SAN ONOFRE',
       'TUCHIN', 'SAN ANDRES ISLAS', 'MARIA LAVAJA', 'SANTA CATALINA',
       'LURUACO', 'LOMA ARENA ', 'SANTA CATALINA BOLIVAR ', 'POLO NUEVO',
       'PUEBLO NUEVO SANTA CATALINA ', 'PUEBLO NUEVO ',
       'MANTIENE ATLANTICO', 'PALMAR DE CANDELARIA ', 'SANTA CATALINA ',
       'PUEBLO NUEVO , SANTA CATALINA ', 'PUEBLO NUEVO', 'PALMAR',
       'LA GUAJIRA ', 'SANTA CATALINA, BOLIVAR', 'SANTA CATALINA BOLIVAR',
       'LIRUACO', 'POLO NUEVO LOMA ARENA ',
       'SANTA CATALINA PUEBLO NUEVO ', 'LOMA ARENA', 'PUEBLI NUEVO',
       'PUEBLO BELLO', 'LOMITA ARENA ', 'MAICAO, LA GUAJIRA',
       'SANTA MARTA ', 'RIOHACHA LA GUAJIRA ', 'LORICA CORDOBA',
       'BOGOTA ', 'MAICAO ', 'SAN ONOFRE, SUCRE ', 'REPELON ATLANTICO ',
       'BARRANQUILLA, ATLANTICO ', 'NORTE DE SANTANDER ',
       'CIENAGA MAGDALENA ', 'BOGOTA CUNDINAMARCA', 'SINCELEJO SUCRE',
       'SOLEDAD ATLANTICO', 'BARRANQUILLA ATLANTICO', 'GALAPA ',
       'CALAMAR, BOLIVAR', 'BARRANQUILLA - ATLANTICO', 'ACHI, BOLIVAR',
       'BARRANQUILLA / ATLANTICO.', 'CORDOBA, BOLIVAR',
       'MAGANGUE / BOLIVAR.', 'VILLANUEVA - LA GUAJIRA',
       'PLATO, MAGDALENA', 'MAICAO LA GUAJIRA ',
       'JUAN DE ACOSTA ATLANTICO ', 'OVEJAS SUCRE ',
       'EL BANCO MAGDALENA ', 'ALBANIA ',
       'SAN PEDRO DE URABA, ANTIOQUIA ', 'VALLLEDUPAR ',
       'RIOACHA GUAJIRA ', 'QUIBDO- CHOCO', 'URUMITA LA GUAJIRA ',
       'VALLEDUPAR CESAR ', 'GUAMAL MAGDALENA ', 'BABBAAH', 'SOLEDAD ',
       'MSGANGUE BOLIVAR', 'SANTA MARTA', 'VILLAVICENCIO',
       ' VILLAVICENCIO ', 'ASTREA CESAR ', 'REMEDIO ANTIOQUIA ',
       'HEREDIA (MAGDALENA)', 'SOLEDAD', 'MOVIL CORDOBA ',
       'CASCAJAL ATLANTICO ', 'RIOACHA', 'POLO NUEVO - ATLANTICO ',
       'CANDELARIA ATLANTICO ', 'CHIBOLO MAGDALENA ', 'BANCO MAGDALENA',
       'JUAN MAL MAGDALENA ', 'GUAMO BOLIVAR', 'BARRANCABERMEJA ',
       'BELLO ANTIOQUIA ', 'MARIA LA BAJA, BOLIVAR ', 'OCANA',
       'PUERTO COLOMBIA ATLANTICO ', 'MAGANGUE- BOLIVAR',
       'SANTA ANA MAGDALENA', 'BUENAVISTA SUCRE ', 'MOMPOX- BOLIVAR ',
       'ALTA GUAJIRA SIAPANA', 'CURACAO', 'SINCELEJO  ', 'CUCUTA',
       'BUCARAMANGA', 'MARACAIBO ', 'TOLIMA', 'CARMEN DE BOLIVAR ',
       'SABANALARGA', 'CIENAGA MAGDALENA', 'MAICAO - LA GUAJIRA ',
       'RIOHACHA - LA GUAJIRA', 'SANTIAGO PUTUYAMO', 'MAICABO',
       'BANCO MAGDALENA ', 'MANTIE', 'MAICAO- LA GUAJIRA',
       'SABANALARGA, ATLANTICO ', 'BARRANQYILLA', 'CIENEGA MAGDALENA',
       'BARRANQUILLA - ATLANTICO ', 'PIVIJAI', 'PASTO ', 'MAICAO',
       'PARAGUACHON', 'EL DIFICIL MAGDALENA ', 'SIN DATO',
       'VALENCIA - VENEZUELA ', 'QUIBDO-CHOCO', 'QUIBDO CHOCO', 'QUIBDO',
       'MATES BOLIVAR ', 'MANAURE CESAR ', 'TENERIFE, MAGDALENA ',
       'BARRANQUILLABATLANTICO', 'SAN PEDRO SUCRE ', 'SACO',
       'SAN JOSE DE SACO ', 'JUAN DE ACOSTA ', 'SAN JOSE DE SACO',
       'SAN JOSE DEL SACO', '1954', 'JUAN DE ACOSTA ATLANTICO',
       'JUAN DE COSTA ', 'SACO JUAN DE ACOSTA', 'JUAN DE ACOSTA',
       'SAN JOSE SE SACO ', 'JUAN DE ACOSYA', 'BARANOA ',
       'PEDRAZA, MAGDALENA ', 'USAN ATLANTICO  ', 'PIVIJAY MAGDALENA ',
       'SALARIAL MAGDALENA', 'PIOJO ', 'SACO JUAN DE ACOSTA ', 'COCORMA',
       'PIVIJAY ', 'SANTUARIO, ANTIOQUIA ', 'SAN JOSE  DE SABO',
       'SACO/ JUAN DE ACOSTA ', 'PUERTO COLOMBIA', 'VALLEDUPAR ',
       'SABANA GRANDE', 'SAN JUAN DE SACO ', 'SAN JOSE DE SAXO', 'SACO ',
       'SABANAGRANDE ', 'PAPAYA ', 'CAMPO DE LA CRUZ ',
       'PALMAR DE CANDELARIA, ATLANTICO', 'CARACAS ', 'POLO NUEVO ',
       'ANORI ANTIOQUIA ', 'SAN DE ACOSTA', 'SANTA CATALINA M',
       'PIOJO- ALTANTICO', 'MANAURE ', 'LOMA ARENA, ATLANTICO', 'ARJONA ',
       'MARIA LA BAJA ', 'CLEMENCIA BOLIVAR ', 'MONTERIA CORDOBA ',
       'CODAZI', 'TUBARA ', 'MALAMBO ', 'MAGANGUE / BOLIVAR ',
       'SANTAROSA', 'CARMEN (BOLIVAR) ', 'CIENAGA, MAGDALENA ',
       'CALAMAR BOLIVAR ', 'CIENAGA- MAGDALENA ',
       'SANTIAGO- NORTE DE SANTANDER ', 'CALAMAR', 'FUNDACION MAGDALENA ',
       'CORDOBA, BOLIVAR ', 'MALAMBO', 'COROZAL - SUCRE', 'MEDELLIN ',
       'BARRANQUILLA / ATLANTICO ', 'RIOACHA ', 'SAN MARCO SUCRE ',
       'PUERTO COLOMBIA / ATLANTICO ', 'MAGANGUE, BOLIVAR ',
       'RIOHACHA, LA GUAJIRA ', 'BARANOA, ATLANTICO ',
       'BUENAS VISTA CORDOBA', 'QUIBDO ',
       'GUACAMAYAL/ CIENAGA/ MAGDALENA', 'ANDES ANTIOQUIA ',
       'PONTEZUELA ', 'PONTEZUELA', 'SAN ONOFRE/ SUCRE',
       'GALERAZAMBA/ SANTA CATALINA/ BOLIVAR',
       'PONTEZUELA/CARTAGENA/BOLIVAR', 'MANZANILLO DEL MAR ',
       'CARTAGENA/BOLIVAR', 'CALAMAR- BOLIVAR ', 'MAGANGUE ',
       'SAN ANDRES ISLAS ', 'SANTO TOMAS ATLANTICO ', 'SINCELEJO SUCRE ',
       'CARTAGENA BOLIVAR ', 'SITIO NUEVO ', 'PEDRAZA MAGDALENA '],
      dtype=object)

In [28]:
df_total["municipio"] = df_total["Lugar de nacimiento "].apply(encontrar_municipio)
df_total["departamento"] = df_total["Lugar de nacimiento "].apply(encontrar_departamento)

In [29]:
df_total.head()

,Tipo Identificación,Lugar de nacimiento,Edad,Genero,Nivel de escolaridad,¿A que regimen pertenece?,Ocupación y/o actividad económica,¿Usted continuamente toma medicinas para la diabetes?,¿Ha tenido diabetes solo durante el embarazo?,¿Algún médico le ha diagnosticado tensión arterial alta?,¿Usted continuamente toma medicinas para la presión arterial alta?,¿Algún médico le ha diagnosticado colesterol alto?,¿Usted continuamente toma medicinas para el colesterol alto?,"¿Algún médico le ha diagnosticado insuficiencia renal crónica? (No incluye piedras en el riñón, infecciones urinarias incontinencia urinaria)",¿Usted alguna vez ha estado en tratamiento en diálisis?,¿Algún médico le ha diagnosticado proteína o sangre en la orina?,"¿Eres alérgico algún tipo de medicamento, alimento o producto?","En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.",¿Consume tabaco o cigarrillo?,¿Ha fumado al menos 100 cigarrillos durante su vida?,¿Por cuántos años ha sido o fue fumador? días Años,¿Consume alcohol?,¿Con que frecuencia usted toma algún tipo debida alcohólica?,¿Toma hasta embriagarse?,¿Consume drogas?,¿Alguna vez ha laborado en campos de cultivo?,¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?,¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?,¿Usted utiliza o ha utilizado abonos y/o fertilizantes?,"¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?",¿Qué método utilizó para aplicar estos pesticidas?,Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?,Durante su trabajo ¿Qué cantidad de líquido consume?,¿Cuándo fue la última vez que visitó a un doctor?,¿Qué tan difícil es para usted tener atención médica?,¿Qué tipo de profesional de salud ha visitado últimamente?,¿Usted cuenta con un médico de cabecera?,¿A qué grupo sanguíneo pertenece?,¿Ha hecho transfusiones previas?,¿Algún miembro de su familia sufre alguna enfermedad?,¿Algún miembro de su familia tiene insuficiencia renal?,Algún miembro de su familia esta en diálisis?,"¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?",¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?,¿Usó medicamentos naturales de forma cotidiana durante el último año?,¿Cuál es tu fuente de agua en el hogar?,Peso,Talla,Indice de masa corporal,Tirilla reactiva,Creatinina (mg/dL),Tasa de filtración glomerular (CDK-EPI),base_de_datos,Fecha de nacimiento,APOL-1,presion_arterial_sistolica,presion_arterial_diastolica,municipio,departamento
0,CEDULA,"BOLIVAR, MARIA LA BAJA",57,FEMENINO,Primaria,Subsidiado,Desempleado,Si,No,Si,Si,Si,Si,No,No,No,No,No aplica,No,No,No aplica,No,Nunca,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 1 litro,Mayor a 3 meses,Muy Dificil,Internista,Si,B+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,63,1.66,22.862534,Negativo,0.9,82.26,1,Desconocido,Desconocido,175.0,89.0,MARIA LA BAJA,BOLIVAR
1,CEDULA,"BARRANQUILLA, ATLANTICO",28,FEMENINO,Secundaria,Subsidiado,Desempleado,No,Sí,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por mes,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 200 cc,Mayor a 3 meses,Difícil,Medico General,No,O+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,75,1.63,28.228386,Negativo,0.7,116.28,1,Desconocido,Desconocido,97.0,70.0,BARRANQUILLA,ATLANTICO
2,CEDULA,"BARRANQUILLA, ATLANTICO",35,FEMENINO,Bachiller,Subsidiado,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por semana,No,No,No,No,No,No,No aplica,No aplica,Dolor de cabeza,Mas de 1 litro,Mayor a dos años,Facil,Medico General,No,O+,No,Hipertensión Arterial,Sí,No,Dolor de cabeza,Si,Si,Suministro municipal,97,1.68,34.367914,Negativo,No realizado,NaN,1,Desconocido,Desconocido,92.0,68.0,BARRANQUILLA,ATLANTICO
3,CEDULA,"CIENAGA, MAGDALENA",19,FEMENINO,Primaria,No tiene,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por mes,No,No,No,No,No,No,No aplica,No aplica,No siente nada,No toma nada,Mayor a dos años,Muy Dificil,Medico General,No,A+,No,Diabetes Mellitus,No,No,Dolor de cabeza,Si,Si,Suministro municipal,65,1.62,24.767566,Negativo,No realizado,NaN,1,Desconocido,Desconocido,105.0,63.0,None,MAGDALENA
4,CEDULA,"SAN JACINTO, BOLIVAR",44,FEMENINO,Bachiller,Subsidiado,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,No,Nunca,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 1 litro,Mayor a dos años,Difícil,Medico General,Si,O+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,70,1.57,28.398718,Negativo,No realizado,NaN,1,Desconocido,Desconocido,126.0,71.0,None,BOLIVAR

In [30]:
diccionario = {
"Edad":"edad",
"Genero ":"genero",
"Nivel de escolaridad":"nivel_escolaridad",
"¿A que regimen pertenece?":"regimen_salud",
"Ocupación y/o actividad económica":"ocupacion",
"¿Usted continuamente toma medicinas para  la diabetes?":"medicinas_para_diabetes",
"¿Ha tenido diabetes solo durante el embarazo?":"diabetes_durante_embarazo",
"¿Algún médico le ha diagnosticado tensión arterial alta?":"antecedentes_presion_alta",
"¿Usted continuamente toma medicinas para la presión arterial alta?":"medicinas_presion_arterial",
"¿Usted continuamente toma medicinas para el colesterol alto?":"medicinas_colesterol_alto",
"¿Ha hecho transfusiones previas?":"transfusiones_previas",
"¿Algún médico le ha diagnosticado insuficiencia renal crónica? (No incluye piedras en el riñón, infecciones urinarias incontinencia urinaria)":"diagnostico_insuficiencia_renal_cronica",
"¿Algún médico le ha diagnosticado proteína o sangre en la orina?":"diagnostico_proteina_sangre_orina",
"¿Algún miembro de su familia tiene insuficiencia renal?":"antecedentes_familia_insuficiencia_renal",
"Algún miembro de su familia esta en diálisis?":"antecedentes_familia_dialisis",
"¿Consume tabaco o cigarrillo?":"consume_tabaco",
"¿Por cuántos años ha sido o fue fumador? días Años":"años_fumador",
"¿Consume alcohol?":"consume_alcohol",
"¿Con que frecuencia usted toma algún tipo debida alcohólica?":"frecuencia_consumo_alcohol",
"¿Toma hasta embriagarse?":"toma_hasta_embriagarse",
"Durante su trabajo ¿Qué cantidad de líquido consume?":"consumo_liquidos_durante_trabajo",
"Peso":"peso",
"Talla":"talla",
"Indice de masa corporal":"imc",
"Creatinina (mg/dL)":"creatinina",
"Tirilla reactiva":"tirilla_reactiva",
"Tasa de filtración glomerular (CDK-EPI)":"tasa_filtracion_glomerular",
"¿Qué tan difícil es para usted tener atención médica?":"facilidad_atencion_medica",
"¿Qué tipo de profesional de salud ha visitado últimamente?":"profesional_visitado",
"¿Usted cuenta con un médico de cabecera?":"medico_cabecera",
"¿Cuándo fue la última vez que visitó a un doctor?":"ultima_visita",
" ¿Usted continuamente toma medicinas para la presión arterial alta?":"medicinas_presion_arterial",
"Tirilla reactiva ":"tirilla_reactiva",
"¿Con que frecuencia usted toma algún tipo debida alcohólica? ":"frecuencia_consumo_alcohol"
}

In [31]:
df_total = df_total.rename(columns=diccionario)

In [32]:
df_total.head()

,Tipo Identificación,Lugar de nacimiento,edad,genero,nivel_escolaridad,regimen_salud,ocupacion,medicinas_para_diabetes,diabetes_durante_embarazo,antecedentes_presion_alta,medicinas_presion_arterial,¿Algún médico le ha diagnosticado colesterol alto?,medicinas_colesterol_alto,diagnostico_insuficiencia_renal_cronica,¿Usted alguna vez ha estado en tratamiento en diálisis?,diagnostico_proteina_sangre_orina,"¿Eres alérgico algún tipo de medicamento, alimento o producto?","En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.",consume_tabaco,¿Ha fumado al menos 100 cigarrillos durante su vida?,años_fumador,consume_alcohol,frecuencia_consumo_alcohol,toma_hasta_embriagarse,¿Consume drogas?,¿Alguna vez ha laborado en campos de cultivo?,¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?,¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?,¿Usted utiliza o ha utilizado abonos y/o fertilizantes?,"¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?",¿Qué método utilizó para aplicar estos pesticidas?,Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?,consumo_liquidos_durante_trabajo,ultima_visita,facilidad_atencion_medica,profesional_visitado,medico_cabecera,¿A qué grupo sanguíneo pertenece?,transfusiones_previas,¿Algún miembro de su familia sufre alguna enfermedad?,antecedentes_familia_insuficiencia_renal,antecedentes_familia_dialisis,"¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?",¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?,¿Usó medicamentos naturales de forma cotidiana durante el último año?,¿Cuál es tu fuente de agua en el hogar?,peso,talla,imc,tirilla_reactiva,creatinina,tasa_filtracion_glomerular,base_de_datos,Fecha de nacimiento,APOL-1,presion_arterial_sistolica,presion_arterial_diastolica,municipio,departamento
0,CEDULA,"BOLIVAR, MARIA LA BAJA",57,FEMENINO,Primaria,Subsidiado,Desempleado,Si,No,Si,Si,Si,Si,No,No,No,No,No aplica,No,No,No aplica,No,Nunca,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 1 litro,Mayor a 3 meses,Muy Dificil,Internista,Si,B+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,63,1.66,22.862534,Negativo,0.9,82.26,1,Desconocido,Desconocido,175.0,89.0,MARIA LA BAJA,BOLIVAR
1,CEDULA,"BARRANQUILLA, ATLANTICO",28,FEMENINO,Secundaria,Subsidiado,Desempleado,No,Sí,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por mes,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 200 cc,Mayor a 3 meses,Difícil,Medico General,No,O+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,75,1.63,28.228386,Negativo,0.7,116.28,1,Desconocido,Desconocido,97.0,70.0,BARRANQUILLA,ATLANTICO
2,CEDULA,"BARRANQUILLA, ATLANTICO",35,FEMENINO,Bachiller,Subsidiado,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por semana,No,No,No,No,No,No,No aplica,No aplica,Dolor de cabeza,Mas de 1 litro,Mayor a dos años,Facil,Medico General,No,O+,No,Hipertensión Arterial,Sí,No,Dolor de cabeza,Si,Si,Suministro municipal,97,1.68,34.367914,Negativo,No realizado,NaN,1,Desconocido,Desconocido,92.0,68.0,BARRANQUILLA,ATLANTICO
3,CEDULA,"CIENAGA, MAGDALENA",19,FEMENINO,Primaria,No tiene,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,Si,1-2 veces por mes,No,No,No,No,No,No,No aplica,No aplica,No siente nada,No toma nada,Mayor a dos años,Muy Dificil,Medico General,No,A+,No,Diabetes Mellitus,No,No,Dolor de cabeza,Si,Si,Suministro municipal,65,1.62,24.767566,Negativo,No realizado,NaN,1,Desconocido,Desconocido,105.0,63.0,None,MAGDALENA
4,CEDULA,"SAN JACINTO, BOLIVAR",44,FEMENINO,Bachiller,Subsidiado,Desempleado,No,No,No,No,No,No,No,No,No,No,No aplica,No,No,No aplica,No,Nunca,No,No,No,No,No,No,No aplica,No aplica,No siente nada,Mas de 1 litro,Mayor a dos años,Difícil,Medico General,Si,O+,No,Hipertensión Arterial,No,No,Ninguno,No,No,Suministro municipal,70,1.57,28.398718,Negativo,No realizado,NaN,1,Desconocido,Desconocido,126.0,71.0,None,BOLIVAR

In [33]:
df_afro_clean.head()

,edad,genero,nivel_escolaridad,regimen_salud,ocupacion,medicinas_para_diabetes,diabetes_durante_embarazo,antecedentes_presion_alta,medicinas_presion_arterial,medicinas_colesterol_alto,transfusiones_previas,diagnostico_insuficiencia_renal_cronica,diagnostico_proteina_sangre_orina,antecedentes_familia_insuficiencia_renal,antecedentes_familia_dialisis,consume_tabaco,años_fumador,consume_alcohol,frecuencia_consumo_alcohol,toma_hasta_embriagarse,consumo_liquidos_durante_trabajo,peso,talla,imc,presion_arterial_sistolica,presion_arterial_diastolica,creatinina,tirilla_reactiva,tasa_filtracion_glomerular,departamento_georeferenciacion,municipio_georeferenciacion,base_de_datos
0,57,Femenino,Primaria,Asegurador público,Desempleado,SI,NO,SI,SI,SI,NO,NO,NO,NO,NO,NO,NaN,NO,Nunca,Negativa,Mas de 1 litro,63.0,1.66,22.862534,175.0,89.0,0.9,Negativa,82.26,BOLIVAR,MARIA LA BAJA,0
1,28,Femenino,Secundaria,Asegurador público,Desempleado,NO,SI,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,SI,1-2 veces por mes,Negativa,Mas de 200 cc,75.0,1.63,28.228386,97.0,70.0,0.7,Negativa,116.28,ATLANTICO,BARRANQUILLA,0
2,35,Femenino,Bachiller,Asegurador público,Desempleado,NO,NO,NO,NO,NO,NO,NO,NO,SI,NO,NO,NaN,SI,1-2 veces por semana,Negativa,Mas de 1 litro,97.0,1.68,34.367914,92.0,68.0,NaN,Negativa,NaN,ATLANTICO,BARRANQUILLA,0
3,19,Femenino,Primaria,No asegurado,Desempleado,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,SI,1-2 veces por mes,Negativa,No toma nada,65.0,1.62,24.767566,105.0,63.0,NaN,Negativa,NaN,ATLANTICO,BARRANQUILLA,0
4,44,Femenino,Bachiller,Asegurador público,Desempleado,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,NO,Nunca,Negativa,Mas de 1 litro,70.0,1.57,28.398718,126.0,71.0,NaN,Negativa,NaN,ATLANTICO,BARRANQUILLA,0

In [34]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
# columnas de cada dataframe
cols_df_total = set(df_total.columns)
cols_clean = set(df_afro_clean.columns)

solo_df1 = sorted(cols_df_total - cols_clean)

# convertir a tabla
tabla = pd.DataFrame({
    "Columnas_solo_en_df_total": solo_df1
})

print(tabla)

                                                                                                              Columnas_solo_en_df_total
0                                                                                                                                APOL-1
1                                              Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?
2                                                       En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.
3                                                                                                                   Fecha de nacimiento
4                                                                                                                  Lugar de nacimiento
5                                                                                                                   Tipo Identificación
6                                                                                                                          departamento
7                                                                                                             facilidad_atencion_medica
8                                                                                                                       medico_cabecera
9                                                                                                                             municipio
10                                                                                                                 profesional_visitado
11                                                                                                                        ultima_visita
12                                                                                                    ¿A qué grupo sanguíneo pertenece?
13                                                             ¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?
14                                                                                        ¿Alguna vez ha laborado en campos de cultivo?
15                                                                                ¿Algún miembro de su familia sufre alguna enfermedad?
16                                                                                   ¿Algún médico le ha diagnosticado colesterol alto?
17                                                                                                                     ¿Consume drogas?
18                                                                                              ¿Cuál es tu fuente de agua en el hogar?
19  ¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?
20                                                                       ¿Eres alérgico algún tipo de medicamento, alimento o producto?
21                                                                                 ¿Ha fumado al menos 100 cigarrillos durante su vida?
22                                                                                  ¿Qué método utilizó para aplicar estos pesticidas?
23                                                                              ¿Usted alguna vez ha estado en tratamiento en diálisis?
24                                                                              ¿Usted utiliza o ha utilizado abonos y/o fertilizantes?
25                                          ¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?
26                                          ¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?
27                                                               ¿Usó medicamentos naturales de forma cotidiana durante el último año?
28                                                          ¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?

In [35]:
df_afro_clean.columns

Index(['edad', 'genero', 'nivel_escolaridad', 'regimen_salud', 'ocupacion',
       'medicinas_para_diabetes', 'diabetes_durante_embarazo',
       'antecedentes_presion_alta', 'medicinas_presion_arterial',
       'medicinas_colesterol_alto', 'transfusiones_previas',
       'diagnostico_insuficiencia_renal_cronica',
       'diagnostico_proteina_sangre_orina',
       'antecedentes_familia_insuficiencia_renal',
       'antecedentes_familia_dialisis', 'consume_tabaco', 'años_fumador',
       'consume_alcohol', 'frecuencia_consumo_alcohol',
       'toma_hasta_embriagarse', 'consumo_liquidos_durante_trabajo', 'peso',
       'talla', 'imc', 'presion_arterial_sistolica',
       'presion_arterial_diastolica', 'creatinina', 'tirilla_reactiva',
       'tasa_filtracion_glomerular', 'departamento_georeferenciacion',
       'municipio_georeferenciacion', 'base_de_datos'],
      dtype='object')

In [36]:
cols_df_total = df_total.columns

In [37]:
categorias(df_total, cols_df_total)

 Tipo Identificación :
['CEDULA' 'CEDULA DE EXTRANJERIA' 'Permiso Temporal (PT)'
 'Permiso temporal ' 'PT' 1003378298 'Cédula de extranjería ' 32877024
 'Permiso por protección temporal ' 'TARJETA DE INDENTIDAD'
 'Permiso de estadía en el país ' 'Permiso de permanencia ']

 Lugar de nacimiento  :
['BOLIVAR, MARIA LA BAJA' 'BARRANQUILLA, ATLANTICO' 'CIENAGA, MAGDALENA'
 'SAN JACINTO, BOLIVAR' 'BARRANQUILLA ' 'SAN BASILIO DE PALENQUE, BOLIVAR'
 'BARRANQUILLA' 'PALENQUE ' 'SAN ONOFRE SUCRE ' 'BARRANQUILLA ATLANTICO '
 'MONTERIA ' 'PUERTO COLOMBIA ' 'SAN PABLO (BOLIVAR)' 'ADANZASU, CALDAS'
 'TUBARA, ATLANTICO' 'ZAMBRANO, BOLIVAR  ' 'SAN PABLO BOLIVAR '
 'TOLU SUCRE' 'VENEZUELA' 'SANTA ANA MAGDALENA ' 'SINCELEJO ' 'CARTAGENA '
 'SANGUN CORDOBA ' 'TENERIFE MAGDALENA ' 'SAGAHUN, CORDOBA ' 'ARENAL'
 'TRUJILLO VENEZUELA ' 'BARANOA' 'SUCRE' 'BOLIVAR ' 'MAHATE (BOLIVAR)'
 'MARIA LA BAJA BOLIVAR ' 'BOMBA, MAGDALENA ' 'CARACAS VENEZUELA '
 'VENEZUELA ' 'GUARANDA ' 'MARIA LA BAJA' 'OVEJAS, SUCRE ' 'CARTAGENA'
 'EL AGARRON, MAGDALENA ' 'SANTA LUCIA ATLANTICO ' 'EL CARMEN DE BOLIVAR'
 'MARIA LA BAJA (BOLIVAR)' 'TIERRA ALTA CORDOBA '
 'VILLA ROSA REPELON ATLANTICO' 'PLATO MAGDALENA ' 'IBAGUE TOLIMA'
 'SAN ESTANISLAO BOLIVAR ' 'MARIA LA BAJA BOLIVAR' 'MOMPOX'
 'CARACAS, VENEZUELA ' 'BARRO BLANCO MAGDALENA ' 'MARACAIBO VENEZUELA '
 'SABANA LARGA ' 'SOLEDAD ATLANTICO ' 'QUIMBAYA QUINDIO '
 'TACAMOCHO BOLIVAR ' 'PALENQUE' 'BARRANQUUILLA' 'CARTAGENA BOLIVAR'
 'VALLEDUPAR' 'CARTAGENA -BOLIVAR' 'MARIALABAJA / BOLIVAR'
 'MAHATES BOLIVAR' 'CARTAGENA - BOLIVAR' 'MONTERIA' 'GALERAZAMBA'
 'SAN ONOFRE' 'TUCHIN' 'SAN ANDRES ISLAS' 'MARIA LAVAJA' 'SANTA CATALINA'
 'LURUACO' 'LOMA ARENA ' 'SANTA CATALINA BOLIVAR ' 'POLO NUEVO'
 'PUEBLO NUEVO SANTA CATALINA ' 'PUEBLO NUEVO ' 'MANTIENE ATLANTICO'
 'PALMAR DE CANDELARIA ' 'SANTA CATALINA '
 'PUEBLO NUEVO , SANTA CATALINA ' 'PUEBLO NUEVO' 'PALMAR' 'LA GUAJIRA '
 'SANTA CATALINA, BOLIVAR' 'SANTA CATALINA BOLIVAR' 'LIRUACO'
 'POLO NUEVO LOMA ARENA ' 'SANTA CATALINA PUEBLO NUEVO ' 'LOMA ARENA'
 'PUEBLI NUEVO' 'PUEBLO BELLO' 'LOMITA ARENA ' 'MAICAO, LA GUAJIRA'
 'SANTA MARTA ' 'RIOHACHA LA GUAJIRA ' 'LORICA CORDOBA' 'BOGOTA '
 'MAICAO ' 'SAN ONOFRE, SUCRE ' 'REPELON ATLANTICO '
 'BARRANQUILLA, ATLANTICO ' 'NORTE DE SANTANDER ' 'CIENAGA MAGDALENA '
 'BOGOTA CUNDINAMARCA' 'SINCELEJO SUCRE' 'SOLEDAD ATLANTICO'
 'BARRANQUILLA ATLANTICO' 'GALAPA ' 'CALAMAR, BOLIVAR'
 'BARRANQUILLA - ATLANTICO' 'ACHI, BOLIVAR' 'BARRANQUILLA / ATLANTICO.'
 'CORDOBA, BOLIVAR' 'MAGANGUE / BOLIVAR.' 'VILLANUEVA - LA GUAJIRA'
 'PLATO, MAGDALENA' 'MAICAO LA GUAJIRA ' 'JUAN DE ACOSTA ATLANTICO '
 'OVEJAS SUCRE ' 'EL BANCO MAGDALENA ' 'ALBANIA '
 'SAN PEDRO DE URABA, ANTIOQUIA ' 'VALLLEDUPAR ' 'RIOACHA GUAJIRA '
 'QUIBDO- CHOCO' 'URUMITA LA GUAJIRA ' 'VALLEDUPAR CESAR '
 'GUAMAL MAGDALENA ' 'BABBAAH' 'SOLEDAD ' 'MSGANGUE BOLIVAR' 'SANTA MARTA'
 'VILLAVICENCIO' ' VILLAVICENCIO ' 'ASTREA CESAR ' 'REMEDIO ANTIOQUIA '
 'HEREDIA (MAGDALENA)' 'SOLEDAD' 'MOVIL CORDOBA ' 'CASCAJAL ATLANTICO '
 'RIOACHA' 'POLO NUEVO - ATLANTICO ' 'CANDELARIA ATLANTICO '
 'CHIBOLO MAGDALENA ' 'BANCO MAGDALENA' 'JUAN MAL MAGDALENA '
 'GUAMO BOLIVAR' 'BARRANCABERMEJA ' 'BELLO ANTIOQUIA '
 'MARIA LA BAJA, BOLIVAR ' 'OCANA' 'PUERTO COLOMBIA ATLANTICO '
 'MAGANGUE- BOLIVAR' 'SANTA ANA MAGDALENA' 'BUENAVISTA SUCRE '
 'MOMPOX- BOLIVAR ' 'ALTA GUAJIRA SIAPANA' 'CURACAO' 'SINCELEJO  '
 'CUCUTA' 'BUCARAMANGA' 'MARACAIBO ' 'TOLIMA' 'CARMEN DE BOLIVAR '
 'SABANALARGA' 'CIENAGA MAGDALENA' 'MAICAO - LA GUAJIRA '
 'RIOHACHA - LA GUAJIRA' 'SANTIAGO PUTUYAMO' 'MAICABO' 'BANCO MAGDALENA '
 'MANTIE' 'MAICAO- LA GUAJIRA' 'SABANALARGA, ATLANTICO ' 'BARRANQYILLA'
 'CIENEGA MAGDALENA' 'BARRANQUILLA - ATLANTICO ' 'PIVIJAI' 'PASTO '
 'MAICAO' 'PARAGUACHON' 'EL DIFICIL MAGDALENA ' 'SIN DATO'
 'VALENCIA - VENEZUELA ' 'QUIBDO-CHOCO' 'QUIBDO CHOCO' 'QUIBDO'
 'MATES BOLIVAR ' 'MANAURE CESAR ' 'TENERIFE, MAGDALENA '
 'BARRANQUILLABATLANTICO' 'SAN PEDRO SUCRE ' 'SACO' 'SAN JOSE DE SACO '
 'JUAN DE ACOSTA ' 'SAN JOSE DE SACO' 'SAN JOSE DEL SACO' '1954'
 'JUAN DE ACOSTA ATLANTICO' 'JUAN DE COSTA ' 'SACO JUAN DE ACOSTA'
 'JUAN DE ACOSTA' 'SAN JOSE SE SACO ' 'JUAN DE ACOSYA' 'BARANOA '
 'PEDRAZA, MAGDALENA ' 'USAN ATLANTICO  ' 'PIVIJAY MAGDALENA '
 'SALARIAL MAGDALENA' 'PIOJO ' 'SACO JUAN DE ACOSTA ' 'COCORMA' 'PIVIJAY '
 'SANTUARIO, ANTIOQUIA ' 'SAN JOSE  DE SABO' 'SACO/ JUAN DE ACOSTA '
 'PUERTO COLOMBIA' 'VALLEDUPAR ' 'SABANA GRANDE' 'SAN JUAN DE SACO '
 'SAN JOSE DE SAXO' 'SACO ' 'SABANAGRANDE ' 'PAPAYA ' 'CAMPO DE LA CRUZ '
 'PALMAR DE CANDELARIA, ATLANTICO' 'CARACAS ' 'POLO NUEVO '
 'ANORI ANTIOQUIA ' 'SAN DE ACOSTA' 'SANTA CATALINA M' 'PIOJO- ALTANTICO'
 'MANAURE ' 'LOMA ARENA, ATLANTICO' 'ARJONA ' 'MARIA LA BAJA '
 'CLEMENCIA BOLIVAR ' 'MONTERIA CORDOBA ' 'CODAZI' 'TUBARA ' 'MALAMBO '
 'MAGANGUE / BOLIVAR ' 'SANTAROSA' 'CARMEN (BOLIVAR) '
 'CIENAGA, MAGDALENA ' 'CALAMAR BOLIVAR ' 'CIENAGA- MAGDALENA '
 'SANTIAGO- NORTE DE SANTANDER ' 'CALAMAR' 'FUNDACION MAGDALENA '
 'CORDOBA, BOLIVAR ' 'MALAMBO' 'COROZAL - SUCRE' 'MEDELLIN '
 'BARRANQUILLA / ATLANTICO ' 'RIOACHA ' 'SAN MARCO SUCRE '
 'PUERTO COLOMBIA / ATLANTICO ' 'MAGANGUE, BOLIVAR '
 'RIOHACHA, LA GUAJIRA ' 'BARANOA, ATLANTICO ' 'BUENAS VISTA CORDOBA'
 'QUIBDO ' 'GUACAMAYAL/ CIENAGA/ MAGDALENA' 'ANDES ANTIOQUIA '
 'PONTEZUELA ' 'PONTEZUELA' 'SAN ONOFRE/ SUCRE'
 'GALERAZAMBA/ SANTA CATALINA/ BOLIVAR' 'PONTEZUELA/CARTAGENA/BOLIVAR'
 'MANZANILLO DEL MAR ' 'CARTAGENA/BOLIVAR' 'CALAMAR- BOLIVAR ' 'MAGANGUE '
 'SAN ANDRES ISLAS ' 'SANTO TOMAS ATLANTICO ' 'SINCELEJO SUCRE '
 'CARTAGENA BOLIVAR ' 'SITIO NUEVO ' 'PEDRAZA MAGDALENA ']

 genero :
['FEMENINO' 'MASCULINO']

 nivel_escolaridad :
['Primaria' 'Secundaria' 'Bachiller' 'No  escolarizado' 'Técnica'
 'Universitaria' 'Posgrado' 'Tecnológa']

 regimen_salud :
['Subsidiado' 'No tiene' 'Contributivo' 'Especial' nan]

 ocupacion :
['Desempleado' 'Otro' 'Agricultor' 'Albañil' 'Comerciante' 'pescador'
 'Ganadero' 'Campesino']

 medicinas_para_diabetes :
['Si' 'No']

 diabetes_durante_embarazo :
['No' 'Sí' 'No aplica']

 antecedentes_presion_alta :
['Si' 'No']

 medicinas_presion_arterial :
['Si' 'No']

 ¿Algún médico le ha diagnosticado colesterol alto? :
['Si' 'No']

 medicinas_colesterol_alto :
['Si' 'No']

 diagnostico_insuficiencia_renal_cronica :
['No' 'Sí']

 ¿Usted alguna vez ha estado en tratamiento en diálisis? :
['No' 'Si']

 diagnostico_proteina_sangre_orina :
['No' 'Si']

 ¿Eres alérgico algún tipo de medicamento, alimento o producto? :
['No' 'Si']

 En caso de ser alérgico indicar el nombre del medicamento, alimento o producto. :
['No aplica' 'Ibuprofeno' 'Antihistamínicos' 'Benzetacil' 'No aplica '
 'Dipirona ' 'Penicilina ' 'Vacuna antitetanica' 'Glutem' 'Diclofenaco'
 'Dipirona y tramadol' 'Alimento: mayonesa ' 'Panadol '
 'Café, huevo, avena, mariscos ' 'Sardina  ' 'Huevo' 'AINES' 'Loratadina'
 'Nimesulida' 'Amoxacilina' 'Penicilina'
 'Acetaminofen dipirona y metoclopramida ' 'Dipirona'
 'Trimetropin - sulfametoxazol' 'Tinidazol' 'Tramadol, dipirona '
 'Amikacina' 'Metacarbamol' 'Ciprofloxacina' 'Acetaminofén' 'Betanetasona'
 'Azitromicina' 'Trimetropin sulfa' 'Ibuprofeno ' 'Losartan'
 'Metoclopramida ' 'AINES, mariscos' 'Ampicilina '
 'Diclofenaco, naproxeno ' 'Contraste ' 'Acetaminofén ' 'Hioscina '
 'Ampicilina' 'Amoxacilina ' 'Novargina' 'Tramadol' 'Loratadina '
 'DICLOFENACO ' 'Ciprofloxacina - trimetropim '
 'Penicilina, mariscos y enlatados ' 'Asa']

 consume_tabaco :
['No' 'Si']

 ¿Ha fumado al menos 100 cigarrillos durante su vida? :
['No' 'Si']

 años_fumador :
['No aplica' 'mayor a 5 años' 'Mayor a 5 años' 'De 3 A 4 años'
 'De 1 a 2 años']

 consume_alcohol :
['No' 'Si']

 frecuencia_consumo_alcohol :
['Nunca' '1-2 veces por mes' '1-2 veces por semana'
 'Menos de 1 vez al mes' 'Cai diario' '3-4 veces por semana' 'Diario']

 toma_hasta_embriagarse :
['No' 'No aplica' 'Si' 'si' 'SI']

 ¿Consume drogas? :
['No' 'Si']

 ¿Alguna vez ha laborado en campos de cultivo? :
['No' 'Si']

 ¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)? :
['No' 'Si']

 ¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)? :
['No' 'Si']

 ¿Usted utiliza o ha utilizado abonos y/o fertilizantes? :
['No' 'Si']

 ¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?  :
['No aplica' 'No' 'Si']

 ¿Qué método utilizó para aplicar estos pesticidas?  :
['No aplica' 'Pulverizador manual' 'Pulverizador de mochila' 'Nebulizador']

 Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas? :
['No siente nada' 'Dolor de cabeza' 'Mareos o desmayo'
 'Boca extremadamente seca' 'Latidos fuertes y rapidos' 'Ardor al orinar'
 'Orina oscura' 'Orina muy escasa' 'Ganas de vomitar']

 consumo_liquidos_durante_trabajo :
['Mas de 1 litro' 'Mas de 200 cc' 'No toma nada' 'Mas de 5 litros'
 'Menos de 100 cc' ' No toma nada']

 ultima_visita :
['Mayor a 3 meses' 'Mayor a dos años' 'Mayor 1 mes'
 'Hace un mes mas o menos' 'Mayor a 1 años' 'Mayor a 6 meses'
 'Hace una  semana mas o menos']

 facilidad_atencion_medica :
['Muy Dificil' 'Difícil' 'Facil' 'Muy Facil']

 profesional_visitado :
['Internista' 'Medico General' 'Enfermera' 'Cardiologo' 'Endocrinologo'
 'Nefrólogo']

 medico_cabecera :
['Si' 'No']

 ¿A qué grupo sanguíneo pertenece? :
['B+' 'O+' 'A+' 'A-' 'O-' 'AB+' 'B-']

 transfusiones_previas :
['No' 'Sí']

 ¿Algún miembro de su familia sufre alguna enfermedad? :
['Hipertensión Arterial' 'Diabetes Mellitus' 'Enfermedad Cardiaca' 'No'
 'Cancer' 'Gastritis cronica' 'Enfermedad Renal' 'ACV '
 'Artritis reumatoide ' 'Neurofibromatosis' 'Hipotiroidismo' 'Parkinson'
 'Colesterol ' 'Hernia lumbosacras ']

 antecedentes_familia_insuficiencia_renal :
['No' 'Sí']

 antecedentes_familia_dialisis :
['No' 'Sí']

 ¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?  :
['Ninguno' 'Dolor de cabeza' 'Fatiga' 'Pérdida de apetito'
 'Dolor de espalda']

 ¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año? :
['No' 'Si']

 ¿Usó medicamentos naturales de forma cotidiana durante el último año?  :
['No' 'Si']

 ¿Cuál es tu fuente de agua en el hogar? :
['Suministro municipal']

 imc :
[22.86253448 28.22838647 34.36791383 24.76756592 28.398718 29.64268547
 30.86419753 23.50780533 36.41975309 26.59279778 23.14725512 20.95717116
 25.47666009 29.71428571 30.45765595 24.38652644 23.83673469 33.53147386
 27.58020032 15.19097222 40.74205925 17.63085399 15.75575085 21.19274242
 30.86303587 23.42236836 35.8836345 26.5625 16.69327914 29.66797122
 20.06920415 23.66524436 29.37239738 17.68978885 32.27078777 15.95965399
 30.66666667 27.17391304 41.09138725 46.56328762 29.77777778 36.57133465
 42.19238103 44.28414901 17.4817898 24.44444444 29.96878252 31.22130395
 15.80588662 15.40562305 11.95941515 9.144947417 28.80441397 15.03105099
 15.36970831 10.92350426 46.86785551 48 33.38655828 38.56749311
 39.35033371 38.26530612 31.37798917 19.8791026 18.36547291 27.28174603
 33.984375 19.9099723 26.06167931 12.96296296 32.04614645 24.62296091
 34.85018427 32.24206349 41.11842105 33.77044866 39.72830962 16.73111243
 21.77384236 25.39021852 27.34375 34.92767916 27.10204082 14.68288168
 25.96454217 26.7755102 24.25867407 26.40235457 28.32658037 17.10451296
 12.57657511 38.57875854 34.66265187 35.91836735 16.40625 25.31545429
 21.23057202 15.77682957 35.49215792 43.40277778 16.88888889 19.605192
 28.69897959 41.20707596 28.08641975 32.0458762 40.79084287 34.765625
 27.05515088 26.25958475 17.28395062 34.99747006 31.58861341 28.57796068
 32.8125 37.94906392 21.96712018 29.70564407 22.49134948 22.85714286
 29.296875 22.48132907 27.58732606 30.11940191 33.59375 39.35250923
 26.29172382 16.89623508 19.02497027 36.88888889 32.46753247 36.21227888
 19.92512982 17.578125 19.37716263 22.72043837 23.30668005 17.50561501
 30.35925114 16.58886617 22.65625 18.68512111 17.7154195 28.125
 30.48315806 25.0995016 35.32123736 16.60899654 23.55555556 23.71184463
 29.0687733 25.23634033 16.796875 34.72057075 31.97501487 29.24210864
 29.33333333 25.10956903 22.7189744 27.63605442 15.91695502 24.14151925
 22.18934911 16.29818594 27.75510204 28.40550436 23.51020408 24.8015873
 28.02768166 28.04037814 16.07012418 27.55555556 23.42355741 24.91349481
 32.421875 26.21882086 28.88888889 31.53011126 21.79930796 23.53036634
 20.76124567 19.36247266 27.47138398 25.10387812 17.31341037 30.81854043
 24.00548697 36.31082062 24.09297052 27.60945176 26.171875 29.75206612 40
 21.62964876 22.32142857 21.49028551 20.65754 23.52941176 32.45567772
 14.20275218 21.79944511 20.81165453 20.54569362 39.8199446 16.02307323
 25.51020408 27.4716889 20.74755019 17.92821543 27.35884546 29.96432818
 26.57312925 29.38475666 34.88985354 25.84776822 25.390625 25.71166208
 35.15625 24.22145329 24.57786715 23.183391 23.01117686 23.72528616
 27.54820937 33.61226848 29.72651605 30.11621315 31.83391003 20.67901235
 34.48415757 28.3446712 20.57142857 23.66143862 23.93948099 21.70512943
 21.97133586 27.6816609 19.95728441 22.91303307 21.2585034 28.72678773
 25.55932916 30.47052154 25.14285714 19.59183673 28.515625 36.85306842
 25.91068435 20.51913409 30.078125 30.85399449 30.11099051 19.84126984
 22.265625 29.666548 23.4375 35.84078259 19.60715661 26.33288875
 25.76298058 18.73048907 39.03681788 18.28989483 27.33564014 26.36560303
 31.5115017 31.8877551 30.85320992 26.6727633 19.15158479 28.90625
 25.71219869 31.55555556 27.23922448 19.83471074 23.828125 30.38501561
 45.1843044 22.67995241 32.59637188 25.63691716 27.74474832 20.54988662
 31.55365915 18.93877551 24.48979592 22.10028959 24.30248706 26.12244898
 28.84153181 25.77777778 24.1671624 31.14186851 23.73866213 37.77777778
 34.68312238 22.14532872 35.29554952 30.47796622 39.95837669 27.734375
 34.62603878 23.33546614 29.34003963 31.22945431 21.09375 32.87197232
 34.29355281 25.6311675 23.03004535 24.97704316 42.66666667 25.82644628
 34.01360544 31.57756239 24.50894577 25.5588462 25.2493372 16.51473114
 32.46618106 25.81663021 18.90203813 24.53512397 39.11111111 26.89232314
 24.41927902 14.3636886 24.38237298 24.21875 26.44628099 30.42719786
 25.46198063 16.52892562 34.375 25.95155709 26.81221871 26.70940171
 22.94811574 24.24242424 28.36035153 19.81767737 26.2345679 25.15315023
 15.94387755 21.87755102 22.64737696 25.21625331 21.4532872 25.90945695
 28.38480216 30.09473 22.53061224 24.43518667 27.05380277 27.01685989
 20.703125 25.34435262 14.1723356 25 34.41319568 27.08415907 33.29864724
 22.60026298 33.15043439 32.86137369 30.42184965 24.15881797 22.15102251
 22.86236854 24.89706023 26.29656684 32.88888889 20.2020202 32.04994797
 32.81807372 32.79194476 24.5389649 19.22768787 24.81632653 24.93372049
 15.67346939 24.609375 26.29757785 19.57633309 32.34681737 21.61281179
 35.55555556 38.28656367 29.21010994 20.19509221 27.25088745 33.76038781
 27.47562949 25.06574622 31.25 31.24523701 34.17489 28.68514468 37.109375
 31.11111111 20.33832645 19.48696145 35.08618043 23.80869017 28.71972318
 16.22783886 22.72440348 29.06592681 32.89473684 24.85795455 29.76190476
 23.80879705 14.34257234 15.38935057 36.14744352 21.30394858 21.21831719
 22.03856749 20.10916403 29.6875 18.90690102 26.0932752 29.06574394
 27.16049383 25.46938776 22.98539751 21.06674327 15.21092482 23.10843458
 18.80920625 26.92743764 23.38435374 26.67487432 33.26214068 16.32653061
 26.43807082 27.81588173 21.5450908 34.89439853 16.80613424 33.62208773
 35.41912633 20.57613169 22.46003435 25.80645161 19.03114187 33.69493754
 26.37023814 28.05570579 35.5998576 21.38593635 21.484375 17.77777778
 22.43230252 37.46097815 33.29369798 26.83864765 38.22222222 17.00680272
 21.2244898 17.14677641 19.88385305 30.82482993 30.44383913 22.79035793
 34.22222222 31.23140988 32.43097158 26.98961938 28.37370242 32.38835543
 31.21748179 34.1932133 31.99217133 32.05128205 18.75 25.60553633
 26.91272587 30.11937557 36.44444444 18.72417355 37.27906671 27.30996814
 33.26706966 29.98358793 25.10239133 36.7901662 16.14152893 22.03172568
 33.77777778 20.79672989 28.95900015 23.87511478 33.203125 29.75778547
 32.8731098 27.88761707 22.79032897 21.2962963 24.33747972 25.53544639
 20.2812331 29.41176471 18.28571429 23.5 36.2 30.1 23.62 21.6 25.1 24 23
 28.1 22.9 28 25.2 21.5 30.8 18 37 31.2 35 32.9 20 36.8 22.1 20.4 31.6 41
 35.6 22 36.1 21.2 26.3 19.9 23.9 34.2 24.2 21.8 '26,9' '23,1' '25,3'
 '24,6' '23,4' '20,07' '19,9' '23,8' nan '26,1' '19,8' 26 27.9 '28,3'
 '26,6' '20,7' 33.3 '30,8' '24,2' 39.5 '22,2' '22,8' 31.7 '30,6' '25,6'
 26.1 '29,2' 35.7 31.3 '23,9' 27.4 '25,1' 32 '25,4' 20.7 '26,3' 32.3 30.9
 18.6 '27,5' '22,9' '24,4' '24,3' 15 '24,7' 23.4 '21,8' 22.8 '24,9' '21,4'
 31 23.1]

 tirilla_reactiva :
['Negativo' 'Positiva']

 creatinina :
[0.9 0.7 'No realizado' 0.8 1 0.6 1.1 1.7 1.2 1.9 1.3 1.5 2 1.8 1.4 1.6
 2.1 2.5 0.841 1.382 0.756 1.524 0.936 1.319 0.791 1.482 0.933 1.58 0.806
 1.405 0.753 1.425 0.904 1.498 0.98 1.511 0.846 1.291 0.821 1.537 0.968
 1.355 0.812 1.596 0.786 1.487 0.972 1.466 0.928 1.317 0.762 1.506 0.964
 1.574 0.934 1.427 0.815 1.413 0.744 1.546 0.952 1.485 0.825 1.298 0.792
 1.59 0.958 1.347 0.805 1.471 0.871 1.469 0.925 1.543 1.508 0.845 0.911
 1.591 0.873 1.329 0.787 1.562 0.975 1.359 0.782 0.916 1.428 0.759 1.521
 0.967 1.31 0.944 1.558 0.826 1.472 0.803 1.307 0.788 0.875 1.366 0.932
 1.453 0.798 1.51 0.748 1.369 0.887 1.434 0.79 1.491 0.946 1.32 0.766
 0.885 1.572 0.955 1.351 0.834 1.443 0.742 1.431 0.921 1.297 0.764 1.549
 0.93 1.386 0.802 1.484 0.855 1.362 0.783 1.423 0.847 1.548 1.309 1.395
 0.917 1.539 1.455 0.831 1.396 0.912 1.513 0.779 1.432 0.858 0.867 1.527
 0.942 1.354 0.795 1.438 1.402 0.809 1.556 0.862 0.918 1.447 0.797 0.896
 1.389 0.743 1.538 1.41 0.945 1.578 1.426 0.784 1.552 1.374 0.844 1.468
 0.829 1.56 0.915 1.401 0.854 1.338 0.926 1.579 0.95 0.839 1.421 1.515
 1.486 0.87 1.373 1.563 1.459 '1.4' 1.542 0.989 0.745 1.112 0.85 1.602
 1.224 1.089 0.897 1.381 1.473 0.658 1.198 0.97 1.356 0.822 1.621 0.813
 1.295 0.732 1.254 0.905 1.514 0.823 1.364 0.995 1.323 0.906 1.457 0.754
 1.609 0.949 1.325 0.678 1.284 0.931 1.372 0.876 1.531 1.357 0.722 0.892
 1.479 1.316 0.799 1.289 0.927 1.601 0.894 1.516 0.746 1.321 0.889 0.977
 0.781 1.299 0.902 0.796 1.306 0.96 1.57 0.872 0.817 0.785 1.303 0.89
 1.583 0.877 1.522 0.828 1.328 0.914 1.492 0.793 1.305 0.998 1.551 1.442
 0.919 1.378 1.458]

 tasa_filtracion_glomerular :
[82.26 116.28 nan 118.1 66.57 110.27 101.98 101.04 113.05 129.36 79.98
 72.73 163.73 109.15 39.69 118.9 121.05 93.92 116.27 58.1 103.92 114.79
 50.35 118.93 118.6 96.87 126.26 64.54 145.76 93.53 66.63 62.3 119.58
 101.26 72.49 108.38 48.94 47.32 35.09 57.8 45.59 82.6 91.58 117.09 107.22
 60.59 115.63 63.2 95.82 143.54 133.98 85.96 88.69 69.11 43.14 45.62 136.4
 83.43 68.47 84.86 84.71 133.08 136.14 90.92 100.84 50.4 34.9 132.1 52.63
 81.61 73.51 92.87 101.03 45.82 33.1 92.69 86.57 70.71 141.72 106.88 74.55
 93.52 69.01 90.49 127.55 127.14 113.04 75.08 148.85 116.05 30.4 54.53
 34.45 40.05 46.56 63.65 33.64 56.96 45.5 35.68 44.36 34.32 92.81 39.61
 78.55 66.01 38.17 35.51 58.09 50.34 40.66 29.17 69.24 30.67 47.36 69.83
 49.15 56.88 60.57 47.26 46.59 70.32 46.98 40.58 61.45 38.25 60.58 30.0
 75.84 58.63 57.76 56.79 28.19 51.99 38.01 82.96 43.53 61.87 50.24 56.86
 35.79 53.2 40.17 23.65 45.41 60.6 30.21 57.41 50.21 43.79 55.88 39.37
 47.03 38.6 40.46 72.08 44.05 36.55 28.56 53.95 45.18 28.22 44.15 31.96
 94.12 76.77 39.89 52.2 59.72 22.14 79.57 105.5 63.88 111.64 58.91 81.27
 98.38 75.92 104.44 32.06 86.66 28.82 41.82 26.1 43.24 82.9 42.74 67.34
 75.54 101.7 106.13 85.31 122.51 129.38 42.53 113.56 50.45 72.67 37.76
 98.14 51.64 115.56 39.15 84.44 59.46 95.38 52.09 88.15 54.37 91.42 58.42
 69.55 52.46 118.64 48.22 109.29 40.25 70.54 56.12 90.35 52.51 87.69 52.45
 112.53 57.07 88.29 70.49 98.07 64.99 137.76 64.85 104.75 54.33 122.72
 60.27 80.76 138.75 124.26 138.77 125.9 124.49 98.75 90.41 39.92 74.5

In [38]:

df_total["frecuencia_consumo_alcohol"] = df_total["frecuencia_consumo_alcohol"].replace({
   
    "Cai diario": 'Casi diario'

})

df_total["regimen_salud"] = df_total["regimen_salud"].replace({
    "Subsidiado": "Asegurador público",
    "No tiene": "No asegurado",
    'Contributivo': 'Asegurador privado',
    'Especial': 'Asegurador privado'
})

df_total["toma_hasta_embriagarse"] = df_total["toma_hasta_embriagarse"].replace({
    "No": "Negativa",
    "Si": "Positiva",
    'si': 'Positiva',
    'SI': 'Positiva'
})

df_total["años_fumador"] = df_total["años_fumador"].replace({
    "mayor a 5 años": "5 años o más",
    "Mayor a 5 años": "5 años o más",
    "De 3 A 4 años": "3 - 4 años",
    'De 1 a 2 años': '1 - 2 años'
})

df_total["tirilla_reactiva"] = df_total["tirilla_reactiva"].replace({
    "Negativo": "Negativa"
})

In [39]:
columnas = ["genero", "ocupacion", "regimen_salud"]

df_total[columnas] = df_total[columnas].apply(lambda x: x.astype(str).str.upper())

In [40]:
columnas = ["genero"]

df_total[columnas] = df_total[columnas].apply(lambda x: x.astype(str).str.capitalize())

In [41]:
import unicodedata

columnas = ["medicinas_para_diabetes", "diabetes_durante_embarazo", "antecedentes_presion_alta", "medicinas_presion_arterial", 
            "medicinas_colesterol_alto", 'transfusiones_previas',  'diagnostico_insuficiencia_renal_cronica', 
            "diagnostico_proteina_sangre_orina", "antecedentes_familia_insuficiencia_renal", "antecedentes_familia_dialisis",
            "consume_tabaco", "consume_alcohol"]

df_total[columnas] = df_total[columnas].apply(
    lambda col: col.astype(str).apply(
        lambda x: unicodedata.normalize("NFKD", x)
        .encode("ascii", "ignore")
        .decode("utf-8")
        .upper()
    )
)

In [42]:
df_nuevo = df_total.copy()

In [43]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1992 entries, 0 to 1991
Data columns (total 59 columns):
 #   Column                                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                                               --------------  -----
 0   Tipo Identificación                                                                                                                  1992 non-null   object
 1   Lugar de nacimiento                                                                                                                  1992 non-null   object
 2   edad                                                                                                                                 1992 non-null   int64
 3   genero                                                                                                                               1992 non-null   object
 4   nivel_escolaridad                                                                                                                    1992 non-null   object
 5   regimen_salud                                                                                                                        1992 non-null   object
 6   ocupacion                                                                                                                            1992 non-null   object
 7   medicinas_para_diabetes                                                                                                              1992 non-null   object
 8   diabetes_durante_embarazo                                                                                                            1992 non-null   object
 9   antecedentes_presion_alta                                                                                                            1992 non-null   object
 10  medicinas_presion_arterial                                                                                                           1992 non-null   object
 11  ¿Algún médico le ha diagnosticado colesterol alto?                                                                                   1992 non-null   object
 12  medicinas_colesterol_alto                                                                                                            1992 non-null   object
 13  diagnostico_insuficiencia_renal_cronica                                                                                              1992 non-null   object
 14  ¿Usted alguna vez ha estado en tratamiento en diálisis?                                                                              1992 non-null   object
 15  diagnostico_proteina_sangre_orina                                                                                                    1992 non-null   object
 16  ¿Eres alérgico algún tipo de medicamento, alimento o producto?                                                                       1992 non-null   object
 17  En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.                                                      1992 non-null   object
 18  consume_tabaco                                                                                                                       1992 non-null   object
 19  ¿Ha fumado al menos 100 cigarrillos durante su vida?                                                                                 1992 non-null   object
 20  años_fumador                                                                                                                         1992 non-null   object
 21  consume_alcohol                                                                                                                      1992 non-null   object
 22  frecuencia_consumo_alcohol                                                                                                           1992 non-null   object
 23  toma_hasta_embriagarse                                                                                                               1992 non-null   object
 24  ¿Consume drogas?                                                                                                                     1992 non-null   object
 25  ¿Alguna vez ha laborado en campos de cultivo?                                                                                        1992 non-null   object
 26  ¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?                                          1992 non-null   object
 27  ¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?                                          1992 non-null   object
 28  ¿Usted utiliza o ha utilizado abonos y/o fertilizantes?                                                                              1992 non-null   object
 29  ¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?                                                              1992 non-null   object
 30  ¿Qué método utilizó para aplicar estos pesticidas?                                                                                   1992 non-null   object
 31  Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?                                             1992 non-null   object
 32  consumo_liquidos_durante_trabajo                                                                                                     1992 non-null   object
 33  ultima_visita                                                                                                                        1992 non-null   object
 34  facilidad_atencion_medica                                                                                                            1992 non-null   object
 35  profesional_visitado                                                                                                                 1992 non-null   object
 36  medico_cabecera                                                                                                                      1992 non-null   object
 37  ¿A qué grupo sanguíneo pertenece?                                                                                                    1992 non-null   object
 38  transfusiones_previas                                                                                                                1992 non-null   object
 39  ¿Algún miembro de su familia sufre alguna enfermedad?                                                                                1992 non-null   object
 40  antecedentes_familia_insuficiencia_renal                                                                                             1992 non-null   object
 41  antecedentes_familia_dialisis                                                                                                        1992 non-null   object
 42  ¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?   1992 non-null   object
 43  ¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?                                                          1992 non-null   object
 44  ¿Usó medicamentos naturales de forma cotidiana durante el último año?                                                                1992 non-null   object
 45  ¿Cuál es tu fuente de agua en el hogar?                                                                                              1992 non-null   object
 46  peso                                                                                                                                 1992 non-null   int64
 47  talla                                                                                                                                1992 non-null   float64
 48  imc                                                                                                                                  1991 non-null   object
 49  tirilla_reactiva                                                                                                                     1992 non-null   object
 50  creatinina                                                                                                                           1992 non-null   object
 51  tasa_filtracion_glomerular                                                                                                           872 non-null    object
 52  base_de_datos                                                                                                                        1992 non-null   object
 53  Fecha de nacimiento                                                                                                                  1992 non-null   object
 54  APOL-1                                                                                                                               1992 non-null   object
 55  presion_arterial_sistolica                                                                                                           1926 non-null   float64
 56  presion_arterial_diastolica                                                                                                          1926 non-null   float64
 57  municipio                                                                                                                            1104 non-null   object
 58  departamento                                                                                                                         483 non-null    object
dtypes: float64(3), int64(2), object(54)
memory usage: 918.3+ KB

In [44]:
df_afro_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2397 entries, 0 to 2396
Data columns (total 32 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   edad                                      2397 non-null   int64
 1   genero                                    2397 non-null   object
 2   nivel_escolaridad                         2397 non-null   object
 3   regimen_salud                             2397 non-null   object
 4   ocupacion                                 2397 non-null   object
 5   medicinas_para_diabetes                   2397 non-null   object
 6   diabetes_durante_embarazo                 2397 non-null   object
 7   antecedentes_presion_alta                 2397 non-null   object
 8   medicinas_presion_arterial                2397 non-null   object
 9   medicinas_colesterol_alto                 2397 non-null   object
 10  transfusiones_previas                     2397 non-null   object
 11  diagnostico_insuficiencia_renal_cronica   2397 non-null   object
 12  diagnostico_proteina_sangre_orina         2397 non-null   object
 13  antecedentes_familia_insuficiencia_renal  2397 non-null   object
 14  antecedentes_familia_dialisis             2397 non-null   object
 15  consume_tabaco                            2397 non-null   object
 16  años_fumador                              850 non-null    object
 17  consume_alcohol                           2397 non-null   object
 18  frecuencia_consumo_alcohol                2397 non-null   object
 19  toma_hasta_embriagarse                    2397 non-null   object
 20  consumo_liquidos_durante_trabajo          2397 non-null   object
 21  peso                                      2397 non-null   float64
 22  talla                                     2397 non-null   float64
 23  imc                                       2397 non-null   float64
 24  presion_arterial_sistolica                2345 non-null   float64
 25  presion_arterial_diastolica               2345 non-null   float64
 26  creatinina                                1302 non-null   float64
 27  tirilla_reactiva                          2397 non-null   object
 28  tasa_filtracion_glomerular                1302 non-null   float64
 29  departamento_georeferenciacion            2346 non-null   object
 30  municipio_georeferenciacion               2346 non-null   object
 31  base_de_datos                             2397 non-null   object
dtypes: float64(7), int64(1), object(24)
memory usage: 599.4+ KB

In [45]:
df_total.columns

Index(['Tipo Identificación', 'Lugar de nacimiento ', 'edad', 'genero',
       'nivel_escolaridad', 'regimen_salud', 'ocupacion',
       'medicinas_para_diabetes', 'diabetes_durante_embarazo',
       'antecedentes_presion_alta', 'medicinas_presion_arterial',
       '¿Algún médico le ha diagnosticado colesterol alto?',
       'medicinas_colesterol_alto', 'diagnostico_insuficiencia_renal_cronica',
       '¿Usted alguna vez ha estado en tratamiento en diálisis?',
       'diagnostico_proteina_sangre_orina',
       '¿Eres alérgico algún tipo de medicamento, alimento o producto?',
       'En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.',
       'consume_tabaco',
       '¿Ha fumado al menos 100 cigarrillos durante su vida?', 'años_fumador',
       'consume_alcohol', 'frecuencia_consumo_alcohol',
       'toma_hasta_embriagarse', '¿Consume drogas?',
       '¿Alguna vez ha laborado en campos de cultivo?',
       '¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?',
       '¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?',
       '¿Usted utiliza o ha utilizado abonos y/o fertilizantes?',
       '¿Al usar estos pesticidas, usó alguna vestimenta o protección especial? ',
       '¿Qué método utilizó para aplicar estos pesticidas? ',
       'Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?',
       'consumo_liquidos_durante_trabajo', 'ultima_visita',
       'facilidad_atencion_medica', 'profesional_visitado', 'medico_cabecera',
       '¿A qué grupo sanguíneo pertenece?', 'transfusiones_previas',
       '¿Algún miembro de su familia sufre alguna enfermedad?',
       'antecedentes_familia_insuficiencia_renal',
       'antecedentes_familia_dialisis',
       '¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda? ',
       '¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?',
       '¿Usó medicamentos naturales de forma cotidiana durante el último año? ',
       '¿Cuál es tu fuente de agua en el hogar?', 'peso', 'talla', 'imc',
       'tirilla_reactiva', 'creatinina', 'tasa_filtracion_glomerular',
       'base_de_datos', 'Fecha de nacimiento', 'APOL-1',
       'presion_arterial_sistolica', 'presion_arterial_diastolica',
       'municipio', 'departamento'],
      dtype='object')

In [46]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
# columnas de cada dataframe
cols_df_total = set(df_total.columns)
cols_clean = set(df_afro_clean.columns)

solo_df1 = sorted(cols_df_total - cols_clean)

# convertir a tabla
tabla = pd.DataFrame({
    "Columnas_solo_en_df_total": solo_df1
})

print(tabla)

                                                                                                              Columnas_solo_en_df_total
0                                                                                                                                APOL-1
1                                              Al final o durante su jornada laboral ¿usted presenta alguno de los siguientes síntomas?
2                                                       En caso de ser alérgico indicar el nombre del medicamento, alimento o producto.
3                                                                                                                   Fecha de nacimiento
4                                                                                                                  Lugar de nacimiento
5                                                                                                                   Tipo Identificación
6                                                                                                                          departamento
7                                                                                                             facilidad_atencion_medica
8                                                                                                                       medico_cabecera
9                                                                                                                             municipio
10                                                                                                                 profesional_visitado
11                                                                                                                        ultima_visita
12                                                                                                    ¿A qué grupo sanguíneo pertenece?
13                                                             ¿Al usar estos pesticidas, usó alguna vestimenta o protección especial?
14                                                                                        ¿Alguna vez ha laborado en campos de cultivo?
15                                                                                ¿Algún miembro de su familia sufre alguna enfermedad?
16                                                                                   ¿Algún médico le ha diagnosticado colesterol alto?
17                                                                                                                     ¿Consume drogas?
18                                                                                              ¿Cuál es tu fuente de agua en el hogar?
19  ¿Durante el último mes ha tenido alguno de los siguientes síntomas: fatiga, pérdida de apetito, dolor de cabeza, dolor de espalda?
20                                                                       ¿Eres alérgico algún tipo de medicamento, alimento o producto?
21                                                                                 ¿Ha fumado al menos 100 cigarrillos durante su vida?
22                                                                                  ¿Qué método utilizó para aplicar estos pesticidas?
23                                                                              ¿Usted alguna vez ha estado en tratamiento en diálisis?
24                                                                              ¿Usted utiliza o ha utilizado abonos y/o fertilizantes?
25                                          ¿Usted utiliza o ha utilizado fungicidas (para matar hongos o enfermedades de las plantas)?
26                                          ¿Usted utiliza o ha utilizado insecticidas y nematicidas (para matar insectos y/o gusanos)?
27                                                               ¿Usó medicamentos naturales de forma cotidiana durante el último año?
28                                                          ¿Usó medicamentos para el dolor (AINES) de forma cotidina en el último año?

In [47]:
columnas_comunes = df_total.columns.intersection(df_afro_clean.columns)

In [48]:
df_comun = df_total[columnas_comunes]

In [49]:
df_comun.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1992 entries, 0 to 1991
Data columns (total 30 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   edad                                      1992 non-null   int64
 1   genero                                    1992 non-null   object
 2   nivel_escolaridad                         1992 non-null   object
 3   regimen_salud                             1992 non-null   object
 4   ocupacion                                 1992 non-null   object
 5   medicinas_para_diabetes                   1992 non-null   object
 6   diabetes_durante_embarazo                 1992 non-null   object
 7   antecedentes_presion_alta                 1992 non-null   object
 8   medicinas_presion_arterial                1992 non-null   object
 9   medicinas_colesterol_alto                 1992 non-null   object
 10  diagnostico_insuficiencia_renal_cronica   1992 non-null   object
 11  diagnostico_proteina_sangre_orina         1992 non-null   object
 12  consume_tabaco                            1992 non-null   object
 13  años_fumador                              1992 non-null   object
 14  consume_alcohol                           1992 non-null   object
 15  frecuencia_consumo_alcohol                1992 non-null   object
 16  toma_hasta_embriagarse                    1992 non-null   object
 17  consumo_liquidos_durante_trabajo          1992 non-null   object
 18  transfusiones_previas                     1992 non-null   object
 19  antecedentes_familia_insuficiencia_renal  1992 non-null   object
 20  antecedentes_familia_dialisis             1992 non-null   object
 21  peso                                      1992 non-null   int64
 22  talla                                     1992 non-null   float64
 23  imc                                       1991 non-null   object
 24  tirilla_reactiva                          1992 non-null   object
 25  creatinina                                1992 non-null   object
 26  tasa_filtracion_glomerular                872 non-null    object
 27  base_de_datos                             1992 non-null   object
 28  presion_arterial_sistolica                1926 non-null   float64
 29  presion_arterial_diastolica               1926 non-null   float64
dtypes: float64(3), int64(2), object(25)
memory usage: 467.0+ KB

In [50]:
df_union = pd.concat([df_afro_clean, df_comun], ignore_index=True)

In [51]:
df_union.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4389 entries, 0 to 4388
Data columns (total 32 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   edad                                      4389 non-null   int64
 1   genero                                    4389 non-null   object
 2   nivel_escolaridad                         4389 non-null   object
 3   regimen_salud                             4389 non-null   object
 4   ocupacion                                 4389 non-null   object
 5   medicinas_para_diabetes                   4389 non-null   object
 6   diabetes_durante_embarazo                 4389 non-null   object
 7   antecedentes_presion_alta                 4389 non-null   object
 8   medicinas_presion_arterial                4389 non-null   object
 9   medicinas_colesterol_alto                 4389 non-null   object
 10  transfusiones_previas                     4389 non-null   object
 11  diagnostico_insuficiencia_renal_cronica   4389 non-null   object
 12  diagnostico_proteina_sangre_orina         4389 non-null   object
 13  antecedentes_familia_insuficiencia_renal  4389 non-null   object
 14  antecedentes_familia_dialisis             4389 non-null   object
 15  consume_tabaco                            4389 non-null   object
 16  años_fumador                              2842 non-null   object
 17  consume_alcohol                           4389 non-null   object
 18  frecuencia_consumo_alcohol                4389 non-null   object
 19  toma_hasta_embriagarse                    4389 non-null   object
 20  consumo_liquidos_durante_trabajo          4389 non-null   object
 21  peso                                      4389 non-null   float64
 22  talla                                     4389 non-null   float64
 23  imc                                       4388 non-null   object
 24  presion_arterial_sistolica                4271 non-null   float64
 25  presion_arterial_diastolica               4271 non-null   float64
 26  creatinina                                3294 non-null   object
 27  tirilla_reactiva                          4389 non-null   object
 28  tasa_filtracion_glomerular                2174 non-null   object
 29  departamento_georeferenciacion            2346 non-null   object
 30  municipio_georeferenciacion               2346 non-null   object
 31  base_de_datos                             4389 non-null   object
dtypes: float64(4), int64(1), object(27)
memory usage: 1.1+ MB

In [52]:
df_union = df_union.drop(columns=["ocupacion", "departamento_georeferenciacion", "municipio_georeferenciacion"])

In [53]:
df_union.head()

,edad,genero,nivel_escolaridad,regimen_salud,medicinas_para_diabetes,diabetes_durante_embarazo,antecedentes_presion_alta,medicinas_presion_arterial,medicinas_colesterol_alto,transfusiones_previas,diagnostico_insuficiencia_renal_cronica,diagnostico_proteina_sangre_orina,antecedentes_familia_insuficiencia_renal,antecedentes_familia_dialisis,consume_tabaco,años_fumador,consume_alcohol,frecuencia_consumo_alcohol,toma_hasta_embriagarse,consumo_liquidos_durante_trabajo,peso,talla,imc,presion_arterial_sistolica,presion_arterial_diastolica,creatinina,tirilla_reactiva,tasa_filtracion_glomerular,base_de_datos
0,57,Femenino,Primaria,Asegurador público,SI,NO,SI,SI,SI,NO,NO,NO,NO,NO,NO,NaN,NO,Nunca,Negativa,Mas de 1 litro,63.0,1.66,22.862534,175.0,89.0,0.9,Negativa,82.26,0
1,28,Femenino,Secundaria,Asegurador público,NO,SI,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,SI,1-2 veces por mes,Negativa,Mas de 200 cc,75.0,1.63,28.228386,97.0,70.0,0.7,Negativa,116.28,0
2,35,Femenino,Bachiller,Asegurador público,NO,NO,NO,NO,NO,NO,NO,NO,SI,NO,NO,NaN,SI,1-2 veces por semana,Negativa,Mas de 1 litro,97.0,1.68,34.367914,92.0,68.0,NaN,Negativa,NaN,0
3,19,Femenino,Primaria,No asegurado,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,SI,1-2 veces por mes,Negativa,No toma nada,65.0,1.62,24.767566,105.0,63.0,NaN,Negativa,NaN,0
4,44,Femenino,Bachiller,Asegurador público,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NaN,NO,Nunca,Negativa,Mas de 1 litro,70.0,1.57,28.398718,126.0,71.0,NaN,Negativa,NaN,0

In [54]:
columnas = df_union.columns.drop("base_de_datos")

n_duplicados = df_union.duplicated(subset=columnas).sum()

print(n_duplicados)

943

In [55]:
import pandas as pd

def obtener_todos_los_duplicados(df, cols_comparar):
    # Convertimos a lista para evitar el KeyError
    lista_cols = list(cols_comparar)
    # keep=False marca todas las ocurrencias de los duplicados
    return df[df.duplicated(subset=lista_cols, keep=False)].copy()

def contar_cruces_entre_bases(df_dups, base_a, base_b, cols_comparar):
    # Convertimos a lista para que pd.merge reconozca las múltiples columnas
    lista_cols = list(cols_comparar)
    
    # Filtramos por base y eliminamos duplicados internos de CADA base 
    # para que el cruce sea "Cuántos registros de A existen en B"
    df_a = df_dups[df_dups['base_de_datos'] == base_a].drop(columns=['base_de_datos']).drop_duplicates()
    df_b = df_dups[df_dups['base_de_datos'] == base_b].drop(columns=['base_de_datos']).drop_duplicates()
    
    # El merge ahora recibirá una lista real de strings
    coincidencias = pd.merge(df_a, df_b, on=lista_cols, how='inner')
    
    return len(coincidencias)

# --- USO DE LAS FUNCIONES CORREGIDO ---

# 1. Definir columnas de comparación como LISTA
cols = df_union.columns.drop("base_de_datos").tolist() 

# 2. Extraer el universo de los 943 duplicados
df_duplicados_total = obtener_todos_los_duplicados(df_union, cols)

# 3. Identificar cruces específicos (ahora sin errores de llave)
cruce_1_2 = contar_cruces_entre_bases(df_duplicados_total, 1, 2, cols)
cruce_0_1 = contar_cruces_entre_bases(df_duplicados_total, 0, 1, cols)
cruce_0_2 = contar_cruces_entre_bases(df_duplicados_total, 0, 2, cols)
# Añadimos el cruce con la base 4 que mencionaste antes
cruce_0_4 = contar_cruces_entre_bases(df_duplicados_total, 0, 4, cols)

print(f"Total registros duplicados en el set (filas totales): {len(df_duplicados_total)}")
print("-" * 40)
print(f"Registros únicos de Base 0 que también aparecen en Base 1: {cruce_0_1}")
print(f"Registros únicos de Base 0 que también aparecen en Base 2: {cruce_0_2}")
print(f"Registros únicos de Base 1 que también aparecen en Base 2: {cruce_1_2}")
print(f"Registros únicos de Base 0 que también aparecen en Base 4: {cruce_0_4}")

Total registros duplicados en el set (filas totales): 1886
----------------------------------------
Registros únicos de Base 0 que también aparecen en Base 1: 0
Registros únicos de Base 0 que también aparecen en Base 2: 0
Registros únicos de Base 1 que también aparecen en Base 2: 0
Registros únicos de Base 0 que también aparecen en Base 4: 0

In [56]:
columnas = df_union.columns.drop("base_de_datos")

duplicados = df_union[df_union.duplicated(subset=columnas, keep=False)]

duplicados.sort_values(by=list(columnas))

,edad,genero,nivel_escolaridad,regimen_salud,medicinas_para_diabetes,diabetes_durante_embarazo,antecedentes_presion_alta,medicinas_presion_arterial,medicinas_colesterol_alto,transfusiones_previas,diagnostico_insuficiencia_renal_cronica,diagnostico_proteina_sangre_orina,antecedentes_familia_insuficiencia_renal,antecedentes_familia_dialisis,consume_tabaco,años_fumador,consume_alcohol,frecuencia_consumo_alcohol,toma_hasta_embriagarse,consumo_liquidos_durante_trabajo,peso,talla,imc,presion_arterial_sistolica,presion_arterial_diastolica,creatinina,tirilla_reactiva,tasa_filtracion_glomerular,base_de_datos
2403,6,Femenino,Primaria,ASEGURADOR PÚBLICO,NO,NO,SI,SI,NO,NO,NO,NO,NO,NO,NO,No aplica,SI,1-2 veces por semana,Negativa,Mas de 1 litro,81.0,1.62,30.864198,150.0,92.0,No realizado,Negativa,NaN,1
3133,6,Femenino,Primaria,ASEGURADOR PÚBLICO,NO,NO,SI,SI,NO,NO,NO,NO,NO,NO,NO,No aplica,SI,1-2 veces por semana,Negativa,Mas de 1 litro,81.0,1.62,30.864198,150.0,92.0,No realizado,Negativa,NaN,1
6,6,Femenino,Primaria,Asegurador público,NO,NO,SI,SI,NO,NO,NO,NO,NO,NO,NO,NaN,SI,1-2 veces por semana,Negativa,Mas de 1 litro,81.0,1.62,30.864198,150.0,92.0,NaN,Negativa,NaN,0
714,6,Femenino,Primaria,Asegurador público,NO,NO,SI,SI,NO,NO,NO,NO,NO,NO,NO,NaN,SI,1-2 veces por semana,Negativa,Mas de 1 litro,81.0,1.62,30.864198,150.0,92.0,NaN,Negativa,NaN,0
2917,10,Femenino,Primaria,ASEGURADOR PÚBLICO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,No aplica,NO,Nunca,Negativa,Menos de 100 cc,78.0,1.55,32.466181,120.0,80.0,No realizado,Negativa,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1303,88,Masculino,Primaria,Asegurador público,NO,No aplica,SI,SI,SI,NO,NO,NO,NO,NO,SI,NaN,NO,Nunca,No aplica,Mas de 1 litro,55.0,1.85,16.070124,110.0,90.0,NaN,Negativa,NaN,0
3987,92,Masculino,Secundaria,ASEGURADOR PÚBLICO,NO,NO APLICA,NO,NO,NO,NO,NO,NO,NO,NO,SI,5 años o más,NO,Nunca,Negativa,Mas de 1 litro,48.0,1.65,17.630854,145.0,88.0,1.542,Positiva,Desconocido,2
4305,92,Masculino,Secundaria,ASEGURADOR PÚBLICO,NO,NO APLICA,NO,NO,NO,NO,NO,NO,NO,NO,SI,5 años o más,NO,Nunca,Negativa,Mas de 1 litro,48.0,1.65,17.630854,145.0,88.0,1.542,Positiva,Desconocido,3
4107,94,Masculino,Primaria,ASEGURADOR PÚBLICO,NO,NO APLICA,NO,NO,NO,NO,NO,NO,NO,NO,NO,No aplica,NO,Nunca,Negativa,Mas de 200 cc,40.0,1.57,16.227839,130.0,80.0,0.904,Positiva,Desconocido,2
4375,94,Masculino,Primaria,ASEGURADOR PÚBLICO,NO,NO APLICA,NO,NO,NO,NO,NO,NO,NO,NO,NO,No aplica,NO,Nunca,Negativa,Mas de 200 cc,40.0,1.57,16.227839,130.0,80.0,0.904,Positiva,Desconocido,3

In [57]:
# Filtramos el dataframe de duplicados para obtener solo los de la base_de_datos 0
tabla_base_0 = duplicados[duplicados['base_de_datos'] == '0'].copy()

# Opcional: Si quieres que la tabla no tenga la columna 'base_de_datos' ya que todos son 0
# tabla_base_0 = tabla_base_0.drop(columns=['base_de_datos'])

print(f"Se han extraído {len(tabla_base_0)} registros duplicados pertenecientes a la Base 0.")
print(tabla_base_0.head())

Se han extraído 848 registros duplicados pertenecientes a la Base 0.
   edad    genero nivel_escolaridad       regimen_salud  \
2    35  Femenino         Bachiller  Asegurador público
3    19  Femenino          Primaria        No asegurado
4    44  Femenino         Bachiller  Asegurador público
5    43  Femenino          Primaria  Asegurador público
6     6  Femenino          Primaria  Asegurador público

  medicinas_para_diabetes diabetes_durante_embarazo antecedentes_presion_alta  \
2                      NO                        NO                        NO
3                      NO                        NO                        NO
4                      NO                        NO                        NO
5                      NO                        NO                        SI
6                      NO                        NO                        SI

  medicinas_presion_arterial medicinas_colesterol_alto transfusiones_previas  \
2                         NO                        NO                    NO
3                         NO                        NO                    NO
4                         NO                        NO                    NO
5                         SI                        NO                    SI
6                         SI                        NO                    NO

  diagnostico_insuficiencia_renal_cronica diagnostico_proteina_sangre_orina  \
2                                      NO                                NO
3                                      NO                                NO
4                                      NO                                NO
5                                      NO                                NO
6                                      NO                                NO

  antecedentes_familia_insuficiencia_renal antecedentes_familia_dialisis  \
2                                       SI                            NO
3                                       NO                            NO
4                                       NO                            NO
5                                       NO                            NO
6                                       NO                            NO

  consume_tabaco años_fumador consume_alcohol frecuencia_consumo_alcohol  \
2             NO          NaN              SI       1-2 veces por semana
3             NO          NaN              SI          1-2 veces por mes
4             NO          NaN              NO                      Nunca
5             NO          NaN              SI          1-2 veces por mes
6             NO          NaN              SI       1-2 veces por semana

  toma_hasta_embriagarse consumo_liquidos_durante_trabajo  peso  talla  \
2               Negativa                   Mas de 1 litro  97.0   1.68
3               Negativa                     No toma nada  65.0   1.62
4               Negativa                   Mas de 1 litro  70.0   1.57
5               Negativa                   Mas de 1 litro  74.0   1.58
6               Negativa                   Mas de 1 litro  81.0   1.62

         imc  presion_arterial_sistolica  presion_arterial_diastolica  \
2  34.367914                        92.0                         68.0
3  24.767566                       105.0                         63.0
4  28.398718                       126.0                         71.0
5  29.642685                       125.0                         83.0
6  30.864198                       150.0                         92.0

  creatinina tirilla_reactiva tasa_filtracion_glomerular base_de_datos
2        NaN         Negativa                        NaN             0
3        NaN         Negativa                        NaN             0
4        NaN         Negativa                        NaN             0
5        NaN         Negativa                        NaN             0
6        NaN         Negativa                        NaN             0

In [61]:
# Filtramos el dataframe de duplicados para obtener solo los de la base_de_datos 0
tabla_base_1 = duplicados[duplicados['base_de_datos'] == '0'].copy()

# Opcional: Si quieres que la tabla no tenga la columna 'base_de_datos' ya que todos son 0
# tabla_base_0 = tabla_base_0.drop(columns=['base_de_datos'])

print(f"Se han extraído {len(tabla_base_1)} registros duplicados pertenecientes a la Base 0.")
print(df_afro_clean.hSSead())

Se han extraído 2397 registros duplicados pertenecientes a la Base 0.

AttributeError: 'DataFrame' object has no attribute 'hSSead'

In [ ]:
# Filtramos el dataframe de duplicados para obtener solo los de la base_de_datos 0
tabla_base_2 = duplicados[duplicados['base_de_datos'] == '2'].copy()

# Opcional: Si quieres que la tabla no tenga la columna 'base_de_datos' ya que todos son 0
# tabla_base_0 = tabla_base_0.drop(columns=['base_de_datos'])

print(f"Se han extraído {len(tabla_base_0)} registros duplicados pertenecientes a la Base 0.")
print(tabla_base_0.head())

Se han extraído 848 registros duplicados pertenecientes a la Base 0.
   edad    genero nivel_escolaridad       regimen_salud  \
2    35  Femenino         Bachiller  Asegurador público
3    19  Femenino          Primaria        No asegurado
4    44  Femenino         Bachiller  Asegurador público
5    43  Femenino          Primaria  Asegurador público
6     6  Femenino          Primaria  Asegurador público

  medicinas_para_diabetes diabetes_durante_embarazo antecedentes_presion_alta  \
2                      NO                        NO                        NO
3                      NO                        NO                        NO
4                      NO                        NO                        NO
5                      NO                        NO                        SI
6                      NO                        NO                        SI

  medicinas_presion_arterial medicinas_colesterol_alto transfusiones_previas  \
2                         NO                        NO                    NO
3                         NO                        NO                    NO
4                         NO                        NO                    NO
5                         SI                        NO                    SI
6                         SI                        NO                    NO

  diagnostico_insuficiencia_renal_cronica diagnostico_proteina_sangre_orina  \
2                                      NO                                NO
3                                      NO                                NO
4                                      NO                                NO
5                                      NO                                NO
6                                      NO                                NO

  antecedentes_familia_insuficiencia_renal antecedentes_familia_dialisis  \
2                                       SI                            NO
3                                       NO                            NO
4                                       NO                            NO
5                                       NO                            NO
6                                       NO                            NO

  consume_tabaco años_fumador consume_alcohol frecuencia_consumo_alcohol  \
2             NO          NaN              SI       1-2 veces por semana
3             NO          NaN              SI          1-2 veces por mes
4             NO          NaN              NO                      Nunca
5             NO          NaN              SI          1-2 veces por mes
6             NO          NaN              SI       1-2 veces por semana

  toma_hasta_embriagarse consumo_liquidos_durante_trabajo  peso  talla  \
2               Negativa                   Mas de 1 litro  97.0   1.68
3               Negativa                     No toma nada  65.0   1.62
4               Negativa                   Mas de 1 litro  70.0   1.57
5               Negativa                   Mas de 1 litro  74.0   1.58
6               Negativa                   Mas de 1 litro  81.0   1.62

         imc  presion_arterial_sistolica  presion_arterial_diastolica  \
2  34.367914                        92.0                         68.0
3  24.767566                       105.0                         63.0
4  28.398718                       126.0                         71.0
5  29.642685                       125.0                         83.0
6  30.864198                       150.0                         92.0

  creatinina tirilla_reactiva tasa_filtracion_glomerular base_de_datos
2        NaN         Negativa                        NaN             0
3        NaN         Negativa                        NaN             0
4        NaN         Negativa                        NaN             0
5        NaN         Negativa                        NaN             0
6        NaN         Negativa                        NaN             0

In [ ]:
import pandas as pd
from pandas.api.types import CategoricalDtype

orden_escolaridad = ['Primaria', 'Secundaria', 'Universitario', 'Posgrado']

# Creamos el "molde" con el orden lógico
tipo_categorico = CategoricalDtype(categories=orden_escolaridad, ordered=True)

In [ ]:
# Aplicamos el cambio a la columna
df_union['nivel_escolaridad'] = df_union['nivel_escolaridad'].astype(tipo_categorico)

In [68]:
df_n1 = df_afro_clean[["edad", "genero", "departamento_georeferenciacion", "municipio_georeferenciacion", "peso","talla"]]

In [69]:
df_n1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2397 entries, 0 to 2396
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   edad                            2397 non-null   int64
 1   genero                          2397 non-null   object
 2   departamento_georeferenciacion  2346 non-null   object
 3   municipio_georeferenciacion     2346 non-null   object
 4   peso                            2397 non-null   float64
 5   talla                           2397 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 112.5+ KB

In [70]:
df_n2 = df_total[["edad", "genero", "departamento_georeferenciacion", "municipio_georeferenciacion", "peso","talla"]]

KeyError: "['departamento_georeferenciacion', 'municipio_georeferenciacion'] not in index"

In [76]:

df_filtrado = df_afro_clean[(df_afro_clean['tasa_filtracion_glomerular'] < 60) & 
                            (df_afro_clean['tirilla_reactiva'] == 'Positiva')]

print(df_filtrado)

      edad     genero nivel_escolaridad       regimen_salud     ocupacion  \
21      92  Masculino        Secundaria  Asegurador público          Otro
26      57   Femenino           Técnica  Asegurador público          Otro
32      39  Masculino           Técnica  Asegurador público    Agricultor
71      43   Femenino         Bachiller  Asegurador público   Desempleado
81      39  Masculino         Bachiller  Asegurador público          Otro
...    ...        ...               ...                 ...           ...
2186    58  Masculino  No  escolarizado  Asegurador público    Agricultor
2221    28   Femenino        Secundaria  Asegurador público  AMA DE CASA
2253    55   Femenino          Primaria  Asegurador público  AMA DE CASA
2257    58   Femenino          Primaria  Asegurador público   AMA DE CASA
2322    64   Femenino        Secundaria  Asegurador público   AMA DE CASA

     medicinas_para_diabetes diabetes_durante_embarazo  \
21                        NO                 No aplica
26                        NO                        NO
32                        NO                 No aplica
71                        NO                        NO
81                        NO                 No aplica
...                      ...                       ...
2186                      NO                 No aplica
2221                      NO                        SI
2253                      NO                        NO
2257                      NO                        NO
2322                      NO                        NO

     antecedentes_presion_alta medicinas_presion_arterial  \
21                          NO                         NO
26                          SI                         SI
32                          NO                         NO
71                          NO                         NO
81                          NO                         NO
...                        ...                        ...
2186                        NO                         NO
2221                        NO                         NO
2253                        NO                         NO
2257                        SI                         SI
2322                        SI                         SI

     medicinas_colesterol_alto transfusiones_previas  \
21                          NO                    NO
26                          NO                    NO
32                          NO                    NO
71                          NO                    NO
81                          NO                    NO
...                        ...                   ...
2186                        NO                    NO
2221                        NO                    NO
2253                        SI                    NO
2257                        NO                    SI
2322                        NO                    NO

     diagnostico_insuficiencia_renal_cronica  \
21                                        NO
26                                        NO
32                                        NO
71                                        NO
81                                        NO
...                                      ...
2186                                      NO
2221                                      NO
2253                                      NO
2257                                      NO
2322                                      NO

     diagnostico_proteina_sangre_orina  \
21                                  NO
26                                  NO
32                                  NO
71                                  SI
81                                  NO
...                                ...
2186                                NO
2221                                NO
2253                                NO
2257                                NO
2322                                NO

     antecedentes_familia_insuficiencia_renal antecedentes_familia_dialisis  \
21                                         NO                            NO
26                                         NO                            NO
32                                         NO                            NO
71                                         NO                            NO
81                                         NO                            NO
...                                       ...                           ...
2186                                       NO                            NO
2221                                       SI                            SI
2253                                       NO                            NO
2257                                       NO                            NO
2322                                       NO                            NO

     consume_tabaco años_fumador consume_alcohol frecuencia_consumo_alcohol  \
21               SI          NaN              NO                      Nunca
26               NO          NaN              NO                      Nunca
32               SI          NaN              NO                      Nunca
71               NO          NaN              NO                      Nunca
81               NO          NaN              NO                      Nunca
...             ...          ...             ...                        ...
2186             NO    No aplica              SI     Menos de 1 vez por mes
2221             NO    No aplica              SI          1-2 veces por mes
2253             NO    No aplica              NO                      Nunca
2257             NO    No aplica              SI       1-2 veces por semana
2322             NO    No aplica              NO                      Nunca

     toma_hasta_embriagarse consumo_liquidos_durante_trabajo  peso  talla  \
21                 Negativa                   Mas de 1 litro  48.0   1.65
26                No aplica                   Mas de 1 litro  84.0   1.53
32                 Negativa                  Mas de 5 litros  79.0   1.64
71                 Negativa                  Mas de 5 litros  72.0   1.71
81                 Negativa                   Mas de 1 litro  85.0   1.56
...                     ...                              ...   ...    ...
2186               Negativa                   Mas de 1 litro  76.0   1.63
2221               Negativa                    Más de 200 cc  74.0   1.62
2253              No aplica                   Mas de 1 litro  68.0   1.60
2257               Positiva                   Mas de 1 litro  60.0   1.53
2322              No aplica                   Mas de 1 litro  76.0   1.56

            imc  presion_arterial_sistolica  presion_arterial_diastolica  \
21    17.630854                       145.0                         88.0
26    35.883634                       154.0                         93.0
32    29.372397                       127.0                         79.0
71    24.622961                       138.0                         88.0
81    34.927679                       135.0                         86.0
...         ...                         ...                          ...
2186  28.604765                       120.0                         70.0
2221  28.196921                       140.0                         76.0
2253  26.562500                       133.0                         80.0
2257  25.631167                       105.0                         82.0
2322  31.229454                       138.0                         80.0

      creatinina tirilla_reactiva  tasa_filtracion_glomerular  \
21          1.70         Positiva                       39.69
26          1.20         Positiva                       58.10
32          1.90         Positiva                       50.35
71          1.50         Positiva                       48.94
81          2.00         Positiva                       47.32
...          ...              ...                         ...
2186        1.50         Positiva                       54.00
2221        1.68         Positiva                       42.00
2253        1.50         Positiva                       41.00
2257        1.10         Positiva                       56.00
2322        2.00         Positiva                       27.00

     departamento_georeferenciacion municipio_georeferenciacion base_de_datos
21                        ATLANTICO                BARRANQUILLA             0
26                        ATLANTICO                BARRANQUILLA             0
32                        ATLANTICO                BARRANQUILLA             0
71                          BOLIVAR     SAN BASILIO DE PALENQUE             0
81                        ATLANTICO                BARRANQUILLA             0
...                             ...                         ...           ...
2186                        BOLIVAR                  HATO VIEJO             0
2221                        BOLIVAR                     CALAMAR             0
2253                        BOLIVAR              BARRANCA VIEJA             0
2257                        BOLIVAR              BARRANCA VIEJA             0
2322                        BOLIVAR                  HATO VIEJO             0

[164 rows x 32 columns]